### ISSUE TITLE
spring-boot 2.x cannot invoke this

### ISSUE THREAD

**Issue by richwxd** [apache/incubator-dubbo-spring-boot-project#108]
When start with spring-boot 2.x, some removed classes is invoked which will cause exception and shutdown immediately.
Can you upgrade the dependencies to spring-boot 2.x and spring 5.x?

**Comment by mercyblitz** [comment]
Please take a look at https://github.com/apache/incubator-dubbo-spring-boot-project/tree/0.2.0 , it will be release soon
