### ISSUE TITLE
zookeeper配置无效？

### ISSUE THREAD

**Issue by levin950825** [apache/incubator-dubbo-spring-boot-project#111]
使用 zookeeper 做注册中心,  提供者发布到服务器后使用的是 `zookeeper://localhost:2181` 消费者 使用的是服务器IP `192.168.0.1` 消费者无法获取提供者。
``` 
dubbo.registry.address=zookeeper://192.168.0.1:2181
dubbo.application.id=battcn-consumer-bookstore
dubbo.application.name=battcn-consumer-bookstore
dubbo.application.qos-port=22223
```

还有是否可以补全一个zk的案例，现在感觉该项目无法运用在生产中。

**Comment by pengls** [comment]
duubo.provider.timeout，duubo.provider.loadbalance，duubo.provider.cluster这些配置都不生效的 ？

**Comment by leicongwu** [comment]
zookeeper出现不了服务提供者，很尴尬

**Comment by liusxg** [comment]
https://github.com/liusxg/springboot-dubbo-zookeeper-demo @levin950825

**Comment by levin950825** [comment]
@liusxg 大兄弟，本地zk我也集成通了，我现在是本地连接服务器ZK和服务器的提供者不通。

**Comment by levin950825** [comment]
@liusxg 我在服务器部署了ZK，provider，那么我本地的consumer没出现在dubbo-admin中

**Comment by levin950825** [comment]
@liusxg 还有你是否有看过日志，你确定这种走的不是dubbo本地直连协议吗

**Comment by pengls** [comment]
dubbo-admin好像只能看到group为dubbo的服务，如果group不是dubbo，不会显示；

**Comment by pengls** [comment]
经过测试发现，duubo.provider.timeout，duubo.provider.loadbalance，duubo.provider.cluster这些配置写在application.properties不会生效，需要写在配置类里，请参考如下：
 @Bean
    public ProviderConfig providerConfig() {
        ProviderConfig providerConfig = new ProviderConfig();
        providerConfig.setTimeout(30000);
        providerConfig.setCluster("failfast");
        providerConfig.setLoadbalance("random");
        return providerConfig;
    }

**Comment by levin950825** [comment]
@pengls 我看代码是没有解析yaml格式的配置

**Comment by pengls** [comment]
@levin950825  不是yaml格式啊，就是properties， 其它配置会读取到，就是上面那几个读取不到

**Comment by pengls** [comment]
我们已经在生产环境使用了，现在量不大，还没发现啥问题

**Comment by liusxg** [comment]
@levin950825 大兄弟你自己咋下载demo试试呢，我确定这个是支持远程的，不是dubbo本地直连的，zookeeper都有链接日志的好吧，你把demo里面的provider和cosumer分别部署在不同的服务器试试，我试了是可以的。
关键在注解这
![image](https://user-images.githubusercontent.com/12162413/39911252-5d7fb696-552d-11e8-8f47-84e8a8f62297.png)

**Comment by levin950825** [comment]
@liusxg  我早期自己试过 ，用的dubbo2.6.1  dubbo-spring-boot-starter 0.2.0

**Comment by levin950825** [comment]
@liusxg 好的  待会fork一份试试 谢谢

**Comment by liusxg** [comment]
cluster有个链接超时时间5s，我暂时不知道在怎么设置，如果出现connectionLoss异常，重新启动就好了。 @levin950825

**Comment by yiyutao** [comment]
服务里面指定了版本，消费者里面就必须指定版本。在配置文件里面指定或在每个消费引用的地方指定都可以。版本要和服务的一致
![image](https://user-images.githubusercontent.com/17490968/45527647-54b57b00-b80f-11e8-94d1-66af2f15f016.png)
![image](https://user-images.githubusercontent.com/17490968/45527670-76166700-b80f-11e8-8539-b7af3c99af5c.png)
