### ISSUE TITLE
dubbo logo print twice

### ISSUE THREAD

**Issue by weibo1987** [apache/incubator-dubbo-spring-boot-project#121]
===2018-04-26 16:56:32.878 INFO  com.alibaba.dubbo.common.logger.LoggerFactory Line:59   - using logger: com.alibaba.dubbo.common.logger.log4j.Log4jLoggerAdapter
===2018-04-26 16:56:32.884 INFO  com.alibaba.boot.dubbo.context.event.WelcomeLogoApplicationListener Line:53   - 

  ████████▄  ███    █▄  ▀█████████▄  ▀█████████▄   ▄██████▄  
  ███   ▀███ ███    ███   ███    ███   ███    ███ ███    ███ 
  ███    ███ ███    ███   ███    ███   ███    ███ ███    ███ 
  ███    ███ ███    ███  ▄███▄▄▄██▀   ▄███▄▄▄██▀  ███    ███ 
  ███    ███ ███    ███ ▀▀███▀▀▀██▄  ▀▀███▀▀▀██▄  ███    ███ 
  ███    ███ ███    ███   ███    ██▄   ███    ██▄ ███    ███ 
  ███   ▄███ ███    ███   ███    ███   ███    ███ ███    ███ 
  ████████▀  ████████▀  ▄█████████▀  ▄█████████▀   ▀██████▀  
                                                             

 :: Dubbo Spring Boot (v0.1.0) : https://github.com/dubbo/dubbo-spring-boot-project
 :: Dubbo (v2.0.1) : https://github.com/alibaba/dubbo
 :: Google group : http://groups.google.com/group/dubbo

===2018-04-26 16:56:32.889 INFO  com.alibaba.boot.dubbo.context.event.OverrideDubboConfigApplicationListener Line:67   - Dubbo Config was overridden by externalized configuration {}
===2018-04-26 16:56:33.004 INFO  org.springframework.context.annotation.AnnotationConfigApplicationContext Line:582  - Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@1573f9fc: startup date [Thu Apr 26 16:56:33 CST 2018]; root of context hierarchy
===2018-04-26 16:56:33.304 INFO  org.hibernate.validator.internal.util.Version Line:30   - HV000001: Hibernate Validator 5.3.5.Final
===2018-04-26 16:56:33.333 INFO  org.springframework.context.support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker Line:325  - Bean 'configurationPropertiesRebinderAutoConfiguration' of type [org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration$$EnhancerBySpringCGLIB$$4614b7a1] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
===2018-04-26 16:56:33.773 INFO  com.alibaba.boot.dubbo.context.event.WelcomeLogoApplicationListener Line:53   - 

  ████████▄  ███    █▄  ▀█████████▄  ▀█████████▄   ▄██████▄  
  ███   ▀███ ███    ███   ███    ███   ███    ███ ███    ███ 
  ███    ███ ███    ███   ███    ███   ███    ███ ███    ███ 
  ███    ███ ███    ███  ▄███▄▄▄██▀   ▄███▄▄▄██▀  ███    ███ 
  ███    ███ ███    ███ ▀▀███▀▀▀██▄  ▀▀███▀▀▀██▄  ███    ███ 
  ███    ███ ███    ███   ███    ██▄   ███    ██▄ ███    ███ 
  ███   ▄███ ███    ███   ███    ███   ███    ███ ███    ███ 
  ████████▀  ████████▀  ▄█████████▀  ▄█████████▀   ▀██████▀  
                                                             

 :: Dubbo Spring Boot (v0.1.0) : https://github.com/dubbo/dubbo-spring-boot-project
 :: Dubbo (v2.0.1) : https://github.com/alibaba/dubbo
 :: Google group : http://groups.google.com/group/dubbo

**Comment by weibo1987** [comment]
anybody here?

**Comment by ralf0131** [comment]
The logo is planning to be removed.

**Comment by weibo1987** [comment]
welcomeLogoListener will regist twice if your application both using springboot and spring cloud.  use args "--spring.cloud.bootstrap.enabled=false" when start springboot application will avoid this issue.
