### ISSUE TITLE
@Reference注解中url可以配置到application.properties中么

### ISSUE THREAD

**Issue by tumao2** [apache/incubator-dubbo-spring-boot-project#129]
@Reference(version = "1.0.0", application = "${dubbo.application.id}", url = "dubbo://localhost:20880")
可以写成这样么
@Reference(version = "1.0.0", application = "${dubbo.application.id}", url = "${dubbo.rpc.test.url}")
在配置文件application.properties中配置
dubbo.rpc.test.url=dubbo://localhost:20880
我像这样写，好像不行，有解决方法么
在线急等，麻烦尽快回复

**Comment by mercyblitz** [comment]
Please use [developing versions](https://github.com/apache/incubator-dubbo-spring-boot-project#developing-versions)

**Comment by 15168326318** [comment]
可以的。
 
![image](https://user-images.githubusercontent.com/38483933/44391974-b01f8080-a563-11e8-8751-dd5f79f151d0.png)

**Comment by 872239537** [comment]
dubbo引用的service和我们工程的service重名怎么写配置文件，使用的是springboot，
@DubboComponentScan("cn.eduplus.bluewhale.*")
@Configuration
public class DubboConfiguration {

    @Bean
    @ConfigurationProperties("dubbo.application")
    public ApplicationConfig applicationConfig() {
        return new ApplicationConfig();
    }

    @Bean(name = "registry0")
    @Qualifier("registry0")
    @ConfigurationProperties("dubbo.registry[0]")
    public RegistryConfig registryConfig() {
        return new RegistryConfig();
    }

    @Bean(name = "registry1")
    @Qualifier("registry1")
    @ConfigurationProperties("dubbo.registry[1]")
    public RegistryConfig registryConfig1() {
        return new RegistryConfig();
    }

    @Bean
    @ConfigurationProperties("dubbo.protocol")
    public ProtocolConfig protocolConfig(){
        return new ProtocolConfig();
    }

    @Bean
    @ConfigurationProperties("dubbo.provider")
    public ProviderConfig providerConfig() {
        return new ProviderConfig();
    }

    @Bean
    @ConfigurationProperties("dubbo.consumer")
    public ConsumerConfig consumerConfig(){
        return new ConsumerConfig();
    }

}


引用：
@Reference(check = false, registry = "registry1", timeout = 10000)
    private IUserService userService2;
为null

**Comment by liujiaxian** [comment]
> 可以的。
> 
> ![image](https://user-images.githubusercontent.com/38483933/44391974-b01f8080-a563-11e8-8751-dd5f79f151d0.png)

I have configured it according to this method. It seems that it is not possible. Did I configure it wrong?
