### ISSUE TITLE
用了springboot+dubbo之后，事务怎么处理，官方没一个例子吗

### ISSUE THREAD

**Issue by piglingcn** [apache/incubator-dubbo-spring-boot-project#130]
用了springboot+dubbo之后，事务怎么处理，官方没一个例子吗

**Comment by mercyblitz** [comment]
Please take a look here : https://github.com/mercyblitz/blogs/blob/master/java/dubbo/Dubbo-Annotation-Driven.md#spring-aop-%E6%94%AF%E6%8C%81
