### ISSUE TITLE
dubbo 2.6.2-SNAPSHOT is not exist

### ISSUE THREAD

**Issue by liusxg** [apache/incubator-dubbo-spring-boot-project#131]
![image](https://user-images.githubusercontent.com/12162413/39865439-730d897e-547f-11e8-8aed-aea173f0d107.png)

![image](https://user-images.githubusercontent.com/12162413/39865065-5028fb88-547e-11e8-92da-fbe660d6ae78.png)

**Comment by upicat** [comment]
//update dubbo 
git clone (or) pull
https://github.com/apache/incubator-dubbo.git
mvn clean install
// then build this project

**Comment by ralf0131** [comment]
Please check the latest README, it is documented there.
