### ISSUE TITLE
The property which is 'dubbo.application.logger', has not effect

### ISSUE THREAD

**Issue by maristonchen** [apache/incubator-dubbo-spring-boot-project#132]
dubbo.application.logger=slf4j
![image](https://user-images.githubusercontent.com/8472013/39883747-583331f4-54ba-11e8-8c4d-21eb283eb515.png)

![image](https://user-images.githubusercontent.com/8472013/39883693-32e3ca76-54ba-11e8-9379-4da58be50972.png)

**Comment by mercyblitz** [comment]
Thank you for reporting, It will be fixed

**Comment by mercyblitz** [comment]
It works.

**Comment by maristonchen** [comment]
thanks

**Comment by HeyChiang** [comment]
This bug still exists in 2.7.8 version.

This is my properties file
`dubbo.application.logger=log4j2`

This is the picture I debugged
![image](https://user-images.githubusercontent.com/12081334/103149325-61bdc480-47a3-11eb-8eec-5673478d3883.png)

when I set `System.setProperty("dubbo.application.logger","log4j2");` , it's ok.
