### ISSUE TITLE
一定要在service里面加这些东西? 不能设置默认值吗。。。

### ISSUE THREAD

**Issue by piglingcn** [apache/incubator-dubbo-spring-boot-project#134]
version = "1.0.0",
        application = "${dubbo.application.id}",
        protocol = "${dubbo.protocol.id}",
        registry = "${dubbo.registry.id}"

**Comment by beiwei30** [comment]
if you don't specify, then the default value will be used.

**Comment by mercyblitz** [comment]
@piglingcn It's optional attributes of `@Service`
