### ISSUE TITLE
刷星星哦

### ISSUE THREAD

**Issue by XUZHOUWANG** [apache/incubator-dubbo-spring-boot-project#135]
![image](https://user-images.githubusercontent.com/2636711/39980298-c4165d9a-577d-11e8-9feb-7526fcaf4a54.png)

please give me a star!!!

haha it's normal!!!

**Comment by XUZHOUWANG** [comment]
这跟在淘宝刷单有什么区别？

**Comment by suclogger** [comment]
@XUZHOUWANG 
推广技术，邀请大家关注和共同推动，这才是社区化的出发点和力量根源。
你完全不了解小马哥的工作和这个项目的意义就开一个无关的issue，你确定你了解这个社区？
有幸观摩了你的博客，感觉你跟我一直以来了解到的有赞的技术氛围格格不入。

**Comment by mercyblitz** [comment]
@XUZHOUWANG @suclogger 两位都是非常关心社区发展的小伙伴，实际上，我想请大家帮忙的原因也是提升社区的活跃度。里面并没有刷单式的利益输送，小伙伴之所以支持主要是因为大家相互帮助，我也在微信群里面答疑解惑，当然这也是交流的一部分。我希望大家共同关注在本工程的发展上，多提出建设性意见和建议，实现社区成长。不希望此等话题不断以及口舌之争，后续我将本 issue 关闭。

*如果本人之前的行为对您的生活有打扰，我在此想您道歉。*

**Comment by XUZHOUWANG** [comment]
希望已价值的方式输出，而非利用famous来做star的堆积。假如项目okay，自然会有人star。而非先找一波人star，再来搞社区什么的。阿里还是很牛逼的。只是不欣赏这种方式。

**Comment by XUZHOUWANG** [comment]
@mercyblitz 

希望用价值的方式输出，而非利用famous来做star的堆积。假如项目okay，自然会有人star。而非先找一波人star，再来搞社区什么的。阿里还是很牛逼的。只是不欣赏这种方式。

**Comment by XUZHOUWANG** [comment]
@suclogger 

你说得对，我完全没有理解他的辛苦，每一份开源都值得鼓励。但是开源项目的价值不是靠刷，而是靠真的提供方便，给企业降低成本。假如认同，大家都会去star它。假如本身就为了star，那么项目本身就没有意义了。

其二，你有幸看了你blog，很不错，比我弄的好。但我是无法推断出你应该适合什么样的技术氛围。你却能推断出我氛围跟有赞格格不入，那是你牛逼。

其三，无关的issue，从你角度认为是无关的。

其四，难道不能有不用意见，明明走错了。
