### ISSUE TITLE
dubbo服务如何启动，会自动shutdown

### ISSUE THREAD

**Issue by MicroCountry** [apache/incubator-dubbo-spring-boot-project#144]
dubbo使用spring boot的启动方式，在idea里面运行会自动shutdown，如果在main函数里面写同步死循环可以解决，但是用dubbox我没遇到这个问题

**Comment by mengxiaofei007** [comment]
同样遇到了这个问题

**Comment by ralf0131** [comment]
Can you post your main method?

**Comment by mercyblitz** [comment]
Please upgrade to [0.1.x](https://github.com/apache/incubator-dubbo-spring-boot-project/tree/0.1.x) for non-web application, starter will block main thread unit shutdown hook signal arrives.
