### ISSUE TITLE
0.2.0自己编译会有问题，是不是没有兼容好2.6.2

### ISSUE THREAD

**Issue by MicroCountry** [apache/incubator-dubbo-spring-boot-project#145]
/Users/apple/git-clone/incubator-dubbo-spring-boot-project/dubbo-spring-boot-actuator/src/main/java/com/alibaba/boot/dubbo/actuate/endpoint/DubboShutdownEndpoint.java:[52,23] 找不到符号

我看源码，dubbo 2.6.2里面ProtocolConfig没有destroyAll方法

**Comment by mengxiaofei007** [comment]
我也是 destroyAll方法被我删了 就通过了..
