### ISSUE TITLE
@Reference 注解里面 version 和 group 参数不支持 属性配置？

### ISSUE THREAD

**Issue by yelove** [apache/incubator-dubbo-spring-boot-project#146]
这很难受啊  版本和环境 写死在代码里 不合适吧

**Comment by mercyblitz** [comment]
Please use master branch to install , it's supported!

**Comment by liyong6351** [comment]
when I clone the master,but can not compile,the error is "incubator-dubbo-spring-boot-project/dubbo-spring-boot-actuator/src/main/java/com/alibaba/boot/dubbo/actuate/endpoint/DubboShutdownEndpoint.java:[52,23] 找不到符号
"
难道这个类有问题？

**Comment by mercyblitz** [comment]
Take latest dubbo
