### ISSUE TITLE
现在支持多协议或者多注册中心，在配置文件中配置吗

### ISSUE THREAD

**Issue by 121635629** [apache/incubator-dubbo-spring-boot-project#150]

**Comment by diecui1202** [comment]
Hi, please reference here for more information, 

Multiple protocol: http://dubbo.apache.org/books/dubbo-user-book/demos/multi-protocols.html
Multiple registry: http://dubbo.apache.org/books/dubbo-user-book/demos/multi-registry.html

**Comment by mercyblitz** [comment]
Please reference [Multiple Dubbo Config Bean Bindings](https://github.com/apache/incubator-dubbo-spring-boot-project/tree/master/dubbo-spring-boot-autoconfigure#multiple-dubbo-config-bean-bindings)
