### ISSUE TITLE
Can you configure multiple protocols in the attribute profile now?

### ISSUE THREAD

**Issue by xianpengopenstudio** [apache/incubator-dubbo-spring-boot-project#153]
@ralf0131 Can you configure multiple protocols in the attribute profile now?

For example:
spring.dubbo.protocol.name=dubbo
spring.dubbo.protocol.port=20880
spring.dubbo.protocol.name=http
spring.dubbo.protocol.port=20881

**Comment by mercyblitz** [comment]
Yes,
```properties
spring.dubbo.protocols.p1.name=dubbo
spring.dubbo.protocols.p1.port=20880
spring.dubbo.protocols.p2.name=http
spring.dubbo.protocols.p2.port=20881
```

**Comment by xianpengopenstudio** [comment]
thanks ！ @mercyblitz
