### ISSUE TITLE
Is Reference support the annotation

### ISSUE THREAD

**Issue by liyong6351** [apache/incubator-dubbo-spring-boot-project#155]
Today I am use @reference to inject the dubbo reference, codes like this

    @Reference(group = "${dubbo.consumer.social.group}",version = "${dubbo.consumer.social.version}")
    private ActivityDubboService activityDubboService;
config like this：
dubbo.consumer.group=uum-service-dev
dubbo.consumer.version=9.0.0
dubbo.consumer.social.group=social-test
dubbo.consumer.social.version=1.0.0

But when the project started,I find that the reference always use the default configuration,shown on the dubbo adminstrator interface:
uum-service-dev/ActivityDubboService:9.0.0

Is there something wrong with myself or the framework?

**Comment by mercyblitz** [comment]
Let me check

**Comment by mercyblitz** [comment]
Please add dependencies in your Maven `pom.xml`, like this:

```xml
<!-- Dubbo -->
<dependency>
    <groupId>com.alibaba</groupId>
    <artifactId>dubbo</artifactId>
    <version>2.6.5</version>
</dependency>
<!-- Spring Context Extras -->
<dependency>
    <groupId>com.alibaba.spring</groupId>
    <artifactId>spring-context-support</artifactId>
    <version>1.0.2</version>
</dependency>
```
