### ISSUE TITLE
请问0.2.0版本什么时候发布，0.1.x版本是否支持spring boot 2.0+ ?

### ISSUE THREAD

**Issue by darren-wang** [apache/incubator-dubbo-spring-boot-project#167]
RT, 请问0.2.0版本什么时候发布，0.1.x版本是否支持spring boot 2.0+ ?

**Comment by ralf0131** [comment]
0.2.0 will be undergoing the Apache release, it is expected to be done in 2-4 week since it is the first Apache release. 

0.1.x supports spring boot 1.5.x, and 0.2.0 supports spring boot 2.0+.
