### ISSUE TITLE
用户手册   连接 404

### ISSUE THREAD

**Issue by vanishma** [apache/incubator-dubbo-spring-boot-project#170]
README.md   和   README_CN.md  文件中的用户手册连接 404

**Comment by mercyblitz** [comment]
How did you do?

**Comment by mercyblitz** [comment]
It works in my side

**Comment by vanishma** [comment]
README_CN.md   --> 快速开始 --> 用户手册
点击后连接是  http://dubbo.io/books/dubbo-user-book/
页面404
