### ISSUE TITLE
0.2.0 怎么不能打包啊

### ISSUE THREAD

**Issue by 806572349** [apache/incubator-dubbo-spring-boot-project#171]
0.2.0 怎么不能打包啊

**Comment by mercyblitz** [comment]
Please give some details

**Comment by 806572349** [comment]
[INFO] Reactor Summary:
[INFO]
[INFO] Dubbo Spring Boot Project .......................... SUCCESS [  0.688 s]
[INFO] Dubbo Spring Boot Parent ........................... SUCCESS [  1.518 s]
[INFO] Dubbo Spring Boot AutoConfigure .................... FAILURE [  7.369 s]
[INFO] Dubbo Spring Boot Starter .......................... SKIPPED
[INFO] Dubbo Spring Boot Actuator ......................... SKIPPED
[INFO] Dubbo Spring Boot Samples .......................... SKIPPED
[INFO] Dubbo Spring Boot Sample : API ..................... SKIPPED
[INFO] Dubbo Spring Boot Sample : Provider ................ SKIPPED
[INFO] Dubbo Spring Boot Sample : Consumer ................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10.137 s
[INFO] Finished at: 2018-06-12T17:50:13+08:00
[INFO] Final Memory: 37M/508M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.rat:apache-rat-plugin:0.12:check (verify.rat) on project dubbo-spring-boot-autoconfigure: Too many files with unapproved license: 2 See RAT report in: E:\DownLoad\Study\Java\Study\Demo\incubator-dubbo-spring-boot-project\dubbo-spring-boot-autoconfigure\target\rat.txt -> [Help 1]

**Comment by darren-wang** [comment]
As we are using spring boot 2.0+, we are waiting dubbo-spring-boot-0.2.x now, is there any timeline when 0.2.x will officially release?
