### ISSUE TITLE
dubbo:method没有注解可以使用，是否在后续加入

### ISSUE THREAD

**Issue by wengwh** [apache/incubator-dubbo-spring-boot-project#179]
dubbo:method没有注解可以使用，是否在后续加入，为了配置method的超时等属性，只能去用xml，不是很舒服。希望可以加注解支持

**Comment by mercyblitz** [comment]
It will be supported on new Dubbo version

**Comment by mercyblitz** [comment]
Please concern about [0.1.2 & 0.2.1 milestone](https://github.com/apache/incubator-dubbo-spring-boot-project/milestone/3)
