### ISSUE TITLE
controller use @Reference throw NullPointerException

### ISSUE THREAD

**Issue by MicroCountry** [apache/incubator-dubbo-spring-boot-project#187]
controller use @Reference throw NullPointerException

![image](https://user-images.githubusercontent.com/16758768/41572482-a1fbb4aa-73aa-11e8-88ac-ace9d18a4b80.png)

1.add method in UserService
2.restart provider and consumer
3.consumer throw NullPointerException 
4.restart provider ,than provider can run normal

**Comment by sarins** [comment]
@mercyblitz I got same error, can u please help for this?

**Comment by mercyblitz** [comment]
@sarins Did you get `@Controller` Bean too early?

**Comment by sarins** [comment]
@mercyblitz 我也不是很清楚，因为刚开始用这个anno的版本，用的是官方的starter 0.2.0版本，dubbo 2.6.2，Springboot 2.0.1，是否需要特殊的配置Springboot入口？求协助，跪谢

**Comment by sarins** [comment]
![image](https://user-images.githubusercontent.com/1165129/42487087-f39941e6-8431-11e8-8264-807d7df2360e.png)

**Comment by sarins** [comment]
![image](https://user-images.githubusercontent.com/1165129/42551789-b11d7938-850b-11e8-8c6f-956eda80d23f.png)

**Comment by sarins** [comment]
@mercyblitz Hi guy, can u please take a look this issue? Does this issue is same with issue #126? and does this issue was fixed? if not which version will fix this issue?

**Comment by mercyblitz** [comment]
Please add  Dubbo 2.6.5  in order to override indirectly dependencies:
```xml
<dependency>
    <groupId>com.alibaba.boot</groupId>
    <artifactId>dubbo-spring-boot-starter</artifactId>
    <version>0.2.0</version>
</dependency>

<!-- Dubbo -->
<dependency>
    <groupId>com.alibaba</groupId>
    <artifactId>dubbo</artifactId>
    <version>2.6.5</version>
</dependency>
<!-- Spring Context Extras -->
<dependency>
    <groupId>com.alibaba.spring</groupId>
    <artifactId>spring-context-support</artifactId>
    <version>1.0.2</version>
</dependency>
```

There was a legacy issue in Dubbo.
