### ISSUE TITLE
Can springframework @service and dubbo @Service coexist?

### ISSUE THREAD

**Issue by 303470934** [apache/incubator-dubbo-spring-boot-project#188]
Does dubbo@service have the features of springframework @service?Can you replace the springframework @sevice?Can we use both annotations on a class at the same time?

**Comment by mercyblitz** [comment]
You can used two annotation at same time.

**Comment by dongyuanlongwang** [comment]
```java
@Service(
        version = "${demo.service.version}",
        application = "${dubbo.application.id}",
        protocol = "${dubbo.protocol.id}",
        registry = "${dubbo.registry.id}"
)
@org.springframework.stereotype.Service
```
like this? too ugly!!!

**Comment by mercyblitz** [comment]
@dongyuanlongwang  

That means it works two `@Service` annotated at same Class , however just use 
```java
@Service(
        version = "${demo.service.version}",
        application = "${dubbo.application.id}",
        protocol = "${dubbo.protocol.id}",
        registry = "${dubbo.registry.id}"
)
```

**Comment by dongyuanlongwang** [comment]
ok, got it . thanks

find the code here `com.alibaba.dubbo.config.spring.beans.factory.annotation.ServiceAnnotationBeanPostProcessor#registerServiceBean`  .

find `com.alibaba.dubbo.config.annotation.Service`, and register as a bean into spring container
![image](https://user-images.githubusercontent.com/17469224/41711178-135347dc-757a-11e8-9b75-dfe41807b4f8.png)

**Comment by mercyblitz** [comment]
You're welcome! That code does check duplicated situation.
