### ISSUE TITLE
dubbo-spring-boot-starter 0.1.0 版本中dubbo.scan.basePackages该项配置所在位置可能导致出问题

### ISSUE THREAD

**Issue by a545347837** [apache/incubator-dubbo-spring-boot-project#190]
在application.properties文件中，dubbo.scan.basePackages 这一项配置的位置如果是放在第一行，会导致程序启动后扫描不到dubbo服务，最终注册不到注册中心中，但将该配置挪到其它地方，比如dubbo.registry.address配置项的下面就正常了。

**Comment by mercyblitz** [comment]
Please try `0.1.1`
