### ISSUE TITLE
0.2.0版本 在maven中心仓库找不到？？

### ISSUE THREAD

**Issue by 276234199** [apache/incubator-dubbo-spring-boot-project#210]
<dependency>
    <groupId>com.alibaba.boot</groupId>
    <artifactId>dubbo-spring-boot-starter</artifactId>
    <version>0.2.0</version>
</dependency>

**Comment by 276234199** [comment]
Missing artifact com.alibaba.boot:dubbo-spring-boot-starter:jar:0.2.0
似乎在阿里的镜像里没有..

**Comment by lovepoem** [comment]
You can see here ：
https://repo.maven.apache.org/maven2/com/alibaba/boot/dubbo-spring-boot-starter/

276234199 <notifications@github.com> 于2018年6月22日周五 上午10:57写道：
