### ISSUE TITLE
项目既是provider又是consumer的问题

### ISSUE THREAD

**Issue by Bo9013** [apache/incubator-dubbo-spring-boot-project#211]
按照https://github.com/apache/incubator-dubbo-spring-boot-project/blob/master/README_CN.md
相关文档配置项目,此项目既是服务提供者,又消费其他的服务,现在出现了这样的问题:
对外提供的服务没问题, 但是消费其他服务时就会卡住,直到超时.

有同学碰到这样的问题么?还是我的配置有问题
开发环境:
java8
springboot2.0.2
dubbo-spring-boot-starte0.2.0
zookeeper

配置信息:
spring.application.name = dubbo-me-demo
	
demo.service.version = 1.0.0

dubbo.scan.basePackages =com.xxx.service

dubbo.application.id = dubbo-me-demo
dubbo.application.name = dubbo-me-demo
dubbo.application.qos.port=22224
dubbo.application.qos.enable=true

dubbo.protocol.id = dubbo
dubbo.protocol.name = dubbo
dubbo.protocol.port = 12346
dubbo.protocol.status = server

dubbo.registry.id = me-registry
dubbo.registry.address =10.10.8.120:2181
dubbo.registry.protocol=zookeeper

management.endpoint.dubbo.enabled = true
management.endpoint.dubbo-shutdown.enabled = true
management.endpoint.dubbo-configs.enabled = true
management.endpoint.dubbo-services.enabled = true
management.endpoint.dubbo-references.enabled = true
management.endpoint.dubbo-properties.enabled = true

management.health.dubbo.status.defaults = memory

management.health.dubbo.status.extras = load,threadpool

**Comment by Bo9013** [comment]
问题解决了,dubbo.protocol.id = dubbo这个地方改为dubbo.protocol.id = zookeeper

**Comment by wuhulala** [comment]
和这个dubbo.protocol.id参数不会有关系把，这不是spring protocol对应的bean 的Id吗
