### ISSUE TITLE
How to put a @Reference instance to spring managed container?

### ISSUE THREAD

**Issue by amit-gshe** [apache/incubator-dubbo-spring-boot-project#217]
I know that the @Reference annotated field will be injected as a rpc proxy but there are some another places where we need to put a singleton Reference bean to spring managed container and then get the refernce by `ApplicationContext.getBean(SomeService.class)`. Because in some place the @Reference can not be scaned and injected such as some short life beans or domain entities. There was a existing [issue](https://github.com/dangdangdotcom/dubbox/issues/261) but was dubbox.

**Comment by amit-gshe** [comment]
So your meaning is that the `@Reference` will put the annotated field to the spring container?

**Comment by mercyblitz** [comment]
@amit-gshe , definitely yes.
