### ISSUE TITLE
The 0.1.1 version of dubbo-spring-boot-autoconfigure-0.1.1.jar does not have spring-configuration-metadata.json

### ISSUE THREAD

**Issue by fuyongde** [apache/incubator-dubbo-spring-boot-project#218]
The 0.1.1 version of dubbo-spring-boot-autoconfigure-0.1.1.jar does not have spring-configuration-metadata.json, which causes IDEA to not prompt automatically.

**Comment by mercyblitz** [comment]
It will be added in `0.1.2`
