### ISSUE TITLE
dubbo参数无法覆盖

### ISSUE THREAD

**Issue by henliqi** [apache/incubator-dubbo-spring-boot-project#222]
dubbo参数application-dev.properties 无法覆盖application.properties中相同的参数
而spring boot是可以覆盖的。

**Comment by mercyblitz** [comment]
Which version ?

**Comment by henliqi** [comment]
i think Dubbo Spring Boot 0.1.0 should Solve the issue,because some one still use jdk which is version below 1.8

**Comment by mercyblitz** [comment]
It's not a Dubbo spring boot issue
