### ISSUE TITLE
please Perfect the document 

### ISSUE THREAD

**Issue by MicroCountry** [apache/incubator-dubbo-spring-boot-project#229]
![image](https://user-images.githubusercontent.com/16758768/42675308-0d2cf852-86a6-11e8-8030-11ac9438fc72.png)
Why didn't write this sentence

> @EnableDubboConfig(multiple = true)

**Comment by mercyblitz** [comment]
`@EnableDubboConfig` `multiple` attribute is `false` as default , that means you only band single config bean for externalized properties, thus You have to set it to be `true`
