### ISSUE TITLE
Spring boot 外部配置文件中dubbo相关配置无效

### ISSUE THREAD

**Issue by iamtt** [apache/incubator-dubbo-spring-boot-project#231]
我在开发以外的环境是这样启动spring boot 项目的
java -jar ./paymentPlatform.jar --spring.config.location= ./paymentPlatform.properties

以此在不同环境下使用不同配置，换上dubbo-spring-boot-starter（0.1.1）后发现
测试环境中，始终读取的都是jar包内的配置，并没有使用外部指定配置，启动报错：

2018-07-16 20:09:48.839 ERROR 18657 --- [           main] org.apache.curator.ConnectionState       : Connection timed out for connection string (192.172.9.9:2181) and timeout (5000) / elapsed (5118)

192.172.9.9:2181 是我故意乱写留在jar包的配置文件内的，
其他数据库连接等dubbo 以外的spring boot 配置能正常取用外部配置文件的。

**Comment by iamtt** [comment]
<dependency>
			<groupId>com.alibaba.boot</groupId>
			<artifactId>dubbo-spring-boot-starter</artifactId>
			<version>0.1.0</version>
		</dependency>
		
		<dependency>
			<groupId>com.alibaba</groupId>
			<artifactId>dubbo</artifactId>
			<version>2.6.1</version>
		</dependency>

**Comment by mercyblitz** [comment]
Please add dependencies in your Maven `pom.xml`, like this:

```xml
<!-- Dubbo -->
<dependency>
    <groupId>com.alibaba</groupId>
    <artifactId>dubbo</artifactId>
    <version>2.6.5</version>
</dependency>
<!-- Spring Context Extras -->
<dependency>
    <groupId>com.alibaba.spring</groupId>
    <artifactId>spring-context-support</artifactId>
    <version>1.0.2</version>
</dependency>
```
