### ISSUE TITLE
Cannot use spring boot profile

### ISSUE THREAD

**Issue by EightMonth** [apache/incubator-dubbo-spring-boot-project#234]
Hi Dubbo team
  its me again
init @Service or @Reference instance is so cool by spring bean post processor,
but maybe spring boot profile active after spring bean post processor then let @Reference or @Service instance used application.yml。
final dubbo context used application.yml before spring boot profile actived.
personal analysis, if its a mistake, please dont mind.

**Comment by mercyblitz** [comment]
Ok, I will investigate

**Comment by mercyblitz** [comment]
It works in next version
