### ISSUE TITLE
NetUtils.getLocalAddress() 在服务器中获取不到地址，求解

### ISSUE THREAD

**Issue by SiGuiyang** [apache/incubator-dubbo-spring-boot-project#236]
![image](https://user-images.githubusercontent.com/25564574/43065860-a982a11a-8e95-11e8-8de6-d22d42b7aa59.png)

**Comment by mercyblitz** [comment]
Which OS and how many net adapters

**Comment by SiGuiyang** [comment]
![image](https://user-images.githubusercontent.com/25564574/43750005-0040e0d6-9a29-11e8-84c7-d6cf9b443aa0.png)
This is my linux system version. If I can make the system run, I have to modify the hosts file. Modify the IP corresponding to the hostname Bogon for the hosts file。

**Comment by mercyblitz** [comment]
Please make a discussion in here: https://github.com/apache/incubator-dubbo/issues
