### ISSUE TITLE
接入后报错ClassNotFoundException: com.alibaba.dubbo.qos.server.DubboLogo

### ISSUE THREAD

**Issue by zqdl6** [apache/incubator-dubbo-spring-boot-project#240]
ClassNotFoundException: com.alibaba.dubbo.qos.server.DubboLogo

**Comment by mercyblitz** [comment]
Which version you used

**Comment by mizhiming521** [comment]
ClassNotFoundException: com.alibaba.dubbo.qos.server.DubboLogo
我也碰到这个问题

 
        <dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo-spring-boot-starter</artifactId>
            <version>${dubbo-spring-boot-starter.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-logging</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.apache.dubbo</groupId>
                    <artifactId>dubbo</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo</artifactId>
            <version>${dubbo.version}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo-registry-nacos</artifactId>
            <version>${dubbo.version}</version>
        </dependency>

        <dependency>
            <groupId>com.alibaba.nacos</groupId>
            <artifactId>nacos-client</artifactId>
            <version>${nacos.version}</version>
        </dependency>


 <dubbo-spring-boot-starter.version>2.7.1</dubbo-spring-boot-starter.version>
        <dubbo.version>2.7.1</dubbo.version>
        <nacos.version>1.0.0-RC3</nacos.version>
