### ISSUE TITLE
spring cloud config server 相关问题

### ISSUE THREAD

**Issue by gt0012** [apache/incubator-dubbo-spring-boot-project#242]
当使用spring cloud config server作为配置中心时，dubbo的start启动快于config的读取，导致dubbo启动配置为空，启动成功，但是没有任何配置，想咨询一下，如果让dubbo在config读取后在启动？

**Comment by mercyblitz** [comment]
How did you code?

**Comment by mercyblitz** [comment]
This is an issue about https://github.com/apache/incubator-dubbo/issues/2897, it will be fixed in Dubbo `2.6.6`
