### ISSUE TITLE
希望解决服务提供者必须先启动的BUG

### ISSUE THREAD

**Issue by yu120** [apache/incubator-dubbo-spring-boot-project#243]
经过测试，发现服务服务提供者必须先启动，然后才能启动服务消费者。否则以下方式使用时一直未null。

```
@Reference(version = "1.0.0", application = "xxx", registry = "xxx")
private IUserService userService;
```
简而言之，就是消费者在订阅到服务提供者之后，没有去更新改字段的值。

**Comment by mercyblitz** [comment]
Thanks for your response , It will be fixed in Dubbo 2.6.4 and dubbo starter 0.1.1

**Comment by zonghaishang** [comment]
@yu120 you can try `@Reference(check=false, ...)`
