### ISSUE TITLE
group  服务分组，当一个接口有多个实现，可以用分组区分 ，不起作用

### ISSUE THREAD

**Issue by nbfujx** [apache/incubator-dubbo-spring-boot-project#246]
group  服务分组，当一个接口有多个实现，可以用分组区分 ，不起作用

org.springframework.context.annotation.ConflictingBeanDefinitionException: Annotation-specified bean name 'channelMerchantProvider' for bean class [com.mipay.polling.provider.v2.ChannelMerchantProvider] conflicts with existing, non-compatible bean definition of same name and class [com.mipay.polling.provider.v1.ChannelMerchantProvider]

**Comment by mercyblitz** [comment]
Which version did you use?

**Comment by nbfujx** [comment]
<dependency>
            <groupId>com.alibaba.boot</groupId>
            <artifactId>dubbo-spring-boot-starter</artifactId>
            <version>0.1.0</version>
        </dependency>

**Comment by nbfujx** [comment]
文件名相同，位于不同的文件夹， 不行  
文件名不相同  可以

**Comment by mercyblitz** [comment]
Please add those Maven dependencies:

```xml
<!-- Dubbo -->
<dependency>
    <groupId>com.alibaba</groupId>
    <artifactId>dubbo</artifactId>
    <version>2.6.5</version>
</dependency>
<!-- Spring Context Extras -->
<dependency>
    <groupId>com.alibaba.spring</groupId>
    <artifactId>spring-context-support</artifactId>
    <version>1.0.2</version>
</dependency>
```

Dubbo 2.6.5 will use the group as a port Service bean name.
