### ISSUE TITLE
application.yml中配置dubbo.scan.base-packages错误导致无法暴露服务问题

### ISSUE THREAD

**Issue by liunancun** [apache/incubator-dubbo-spring-boot-project#247]
在spring-configuration-metadata.json文件中定义的是dubbo.scan.base-packages
{
  "sourceType": "com.alibaba.boot.dubbo.autoconfigure.DubboScanProperties",
  "name": "dubbo.scan.base-packages",
  "description": "The basePackages to scan , the multiple-value is delimited by comma\n\n @see EnableDubbo#scanBasePackages()",
  "type": "java.util.Set<java.lang.String>"
}

实际在代码中取值的时候用的又是dubbo.scan.basePackages
Set<String> packagesToScan = environment.getProperty(BASE_PACKAGES_PROPERTY_NAME, Set.class, emptySet());
public static final String BASE_PACKAGES_PROPERTY_NAME = DUBBO_SCAN_PREFIX + PROPERTY_NAME_SEPARATOR + "basePackages";

导致无法正确扫描，无法保留服务。

**Comment by laurelcc** [comment]
yml文件配置确实会出问题，我使用同样的参数配置成properties格式后，服务就正常了

**Comment by cjp1016** [comment]
确实是的，源代码的取值和metadata.json不一致

**Comment by mercyblitz** [comment]
Please add  Dubbo 2.6.5  in order to override indirectly dependencies:
```xml
<dependency>
    <groupId>com.alibaba.boot</groupId>
    <artifactId>dubbo-spring-boot-starter</artifactId>
    <version>0.2.0</version>
</dependency>

<!-- Dubbo -->
<dependency>
    <groupId>com.alibaba</groupId>
    <artifactId>dubbo</artifactId>
    <version>2.6.5</version>
</dependency>
<!-- Spring Context Extras -->
<dependency>
    <groupId>com.alibaba.spring</groupId>
    <artifactId>spring-context-support</artifactId>
    <version>1.0.2</version>
</dependency>
```

There was a legacy issue in Dubbo.
