### ISSUE TITLE
怎么使用注解的方式设置方法级别的重试

### ISSUE THREAD

**Issue by VolcanoOves** [apache/incubator-dubbo-spring-boot-project#251]
<dubbo:service interface="xxx" ref="xxxxService" version="1.0.0" timeout="1000" retries="2" loadbalance="random" delay="-1">
        <dubbo:method name="insertXX" retries="0"/>
        <dubbo:method name="getXX" retries="3"/>
        <dubbo:method name="getXX" retries="0"/>
</dubbo:service>

上面是XML配置方法级别的重试，那么通过注解该如何实现呢？

**Comment by VolcanoOves** [comment]
刚看到您说到下个版本会加上该功能的注解实现~，方便透露下下个版本时间计划吗？谢谢。

**Comment by mercyblitz** [comment]
It's a feature of dubbo, and will be release in dubbo 2.6.4 and 2.7.0
