### ISSUE TITLE
spring-boot dubbo 如何打包provide服务？

### ISSUE THREAD

**Issue by 65725738** [apache/incubator-dubbo-spring-boot-project#258]
这里有个问题。没时间去看源码，问一下。
官方dubbo简单的例子，
 public static void main(String[] args) throws Exception {
        ClassPathXmlApplicationContext context = new ClassPathXmlApplicationContext(new String[] {"http://10.20.160.198/wiki/display/dubbo/provider.xml"});
        context.start();
        System.in.read(); // 按任意键退出
    }
这里面如果   System.in.read(); 不加的话，程序会退出来。这个是为什么呢？
provide肯定会绑定端口提供服务的。为什么需要主线程hold住。难道刚开始的时候没初始化，初始化都是放在Daemon线程里面吗？netty 还是mina 应该都会绑定一个端口之后不会退出程序呀。

com.alibaba.dubbo.container.Main这个类里面也需要hold主线程
     try {
            LOCK.lock();
            STOP.await();
        } catch (InterruptedException e) {
            logger.warn("Dubbo service server stopped, interrupted by other thread!", e);
        } finally {
            LOCK.unlock();
        }

如果用springboot 加dubbo 。如何打包程序。

直接用spring-boot-maven-plugin打包成jar 。可以吗？

**Comment by mercyblitz** [comment]
Please reference [provider sample](https://github.com/apache/incubator-dubbo-spring-boot-project/tree/master/dubbo-spring-boot-samples/dubbo-spring-boot-sample-provider)
