### ISSUE TITLE
SerializationOptimizer 功能还没有实现么？

### ISSUE THREAD

**Issue by zivszheng** [apache/incubator-dubbo-spring-boot-project#259]
// TODO add this to provider config
private String optimizer;

public class SerializationOptimizerImpl implements SerializationOptimizer {
    public Collection<Class> getSerializableClasses() {
        List<Class> classes = new LinkedList<>();
        // 需要序列化的bean
        classes.add(ObjectBean.class);
        return classes;
    }
}

**Comment by mercyblitz** [comment]
Please report issue to #apache/incubator-dubbo
