### ISSUE TITLE
八百里加急：多协议配置和同一个接口同时暴露多个协议报错，已经升级到0.2.0版本了

### ISSUE THREAD

**Issue by 15168326318** [apache/incubator-dubbo-spring-boot-project#262]
![image](https://user-images.githubusercontent.com/38483933/44390690-7bf69080-a560-11e8-95b4-e450d24054b1.png)

**Comment by 15168326318** [comment]
求解答

**Comment by mercyblitz** [comment]
The same issue , please take a look at #263
