### ISSUE TITLE
0.2.0 Samples project using maven install failure

### ISSUE THREAD

**Issue by pengminxuan** [apache/incubator-dubbo-spring-boot-project#264]
[INFO] Reactor Summary:
[INFO] 
[INFO] Dubbo Spring Boot Samples .......................... SUCCESS [  1.585 s]
[INFO] Dubbo Spring Boot Sample : API ..................... FAILURE [  0.829 s]
[INFO] Dubbo Spring Boot Sample : Provider ................ SKIPPED
[INFO] Dubbo Spring Boot Sample : Consumer ................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.791 s
[INFO] Finished at: 2018-08-27T10:47:29+08:00
[INFO] Final Memory: 26M/330M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.rat:apache-rat-plugin:0.12:check (verify.rat) on project dubbo-spring-boot-sample-api: Too many files with unapproved license: 1 See RAT report in: D:\Java Project\github\dubbo-spring-boot-samples\dubbo-spring-boot-sample-api\target\rat.txt -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :dubbo-spring-boot-sample-api

**Comment by mercyblitz** [comment]
It's not an issue, please refer  apache-rat-plugin
