### ISSUE TITLE
想比较方便的获取所有dubbo相关的配置，如何获取？

### ISSUE THREAD

**Issue by yuyunqing28** [apache/incubator-dubbo-spring-boot-project#265]
https://github.com/alibaba/dubbo-spring-boot-starter
之前用过这个版本（2.0.0），有DubboProperties可用。现在用dubbo-spring-boot-starter（0.1.1），发现这个类找不到了。如果想比较方便的获取所有dubbo相关的配置，如何获取呢？

**Comment by mercyblitz** [comment]
You could reference this document : 

https://github.com/apache/incubator-dubbo-spring-boot-project/tree/master/dubbo-spring-boot-actuator#actuatordubboproperties
