### ISSUE TITLE
0.2.0版本有问题

### ISSUE THREAD

**Issue by coolrainman** [apache/incubator-dubbo-spring-boot-project#266]
![image](https://user-images.githubusercontent.com/3948331/44718826-eaed5f80-aaf3-11e8-9764-ea5dc69bdabc.png)
![image](https://user-images.githubusercontent.com/3948331/44718866-0e180f00-aaf4-11e8-8581-37abab26eb5c.png)

请教下，如何解决

**Comment by feelinglucky** [comment]
什么 IDE，重新 Build 一遍看看？

**Comment by mercyblitz** [comment]
IDE maven dependencies issue
