### ISSUE TITLE
Springboot1.5.10.RELEASE yml配置文件cunsumer配置无法自动注入问题

### ISSUE THREAD

**Issue by uzdz** [apache/incubator-dubbo-spring-boot-project#273]
spring1.5.x版本与dubbo-spring-boot-starter0.1.0，配置cunsumer yml资源文件，dubbo无法解析？
举例
# dubbo配置
dubbo:
  consumer:
    check: false
上述配置，在springboot1.5.x版本与dubbo-spring-boot-starter0.1.0版本中无效。

换成springboot2.0.4和dubbo-spring-boot-starter 0.2.0得以解决，或手动注入ConsumerConfig Bean解决

**Comment by mercyblitz** [comment]
You also can update Dubbo latest version

**Comment by uzdz** [comment]
> You also can update Dubbo latest version

是的，升级到springboot2.x和dubbo-spring-boot-starter0.2.0是可以解决的。
经过我们排查，怀疑可能是dubbo-spring-boot-starter0.1.0内引用的dubbo版本可能与springboot1.5.x版本兼容存在bug。

**Comment by mercyblitz** [comment]
Please add dependencies in your Maven `pom.xml`, like this:

```xml
<!-- Dubbo -->
<dependency>
    <groupId>com.alibaba</groupId>
    <artifactId>dubbo</artifactId>
    <version>2.6.5</version>
</dependency>
<!-- Spring Context Extras -->
<dependency>
    <groupId>com.alibaba.spring</groupId>
    <artifactId>spring-context-support</artifactId>
    <version>1.0.2</version>
</dependency>
```
