### ISSUE TITLE
dubbo-spring-boot-starter 0.2.0真心垃圾

### ISSUE THREAD

**Issue by yumrko** [apache/incubator-dubbo-spring-boot-project#274]
这和spring boot 2.x 出现各种问题 各种注册不上 本地bug 整合mybatis 更是恶心的一x

**Comment by ralf0131** [comment]
Please provide detailed issues.

**Comment by yumrko** [comment]
有个用0.1.0 版本的 整合 spring boot1.5.15 还是可以的 不过我找到的是 mybatis plus + spring boot + dubbo 本地 zkServer.cmd  redis.exe 运行起来  加上 shiro 是可以跑起来的。不知道部署到服务器上会不会崩溃

**Comment by mercyblitz** [comment]
What's error message?

**Comment by yumrko** [comment]
问题以解决 部署了 0.1.0版本 个0.2.0版本

**Comment by JunjianS** [comment]
这个工程和alibaba下面的那个starter工程什么关系？

**Comment by ralf0131** [comment]
@JunjianS  This is the official starter.
