### ISSUE TITLE
dubbo-spring-boot-starter  pom.xml

### ISSUE THREAD

**Issue by wr1ttenyu** [apache/incubator-dubbo-spring-boot-project#275]
```
 <dependency>
           <groupId>org.springframework.boot</groupId>
           <artifactId>spring-boot-starter</artifactId>
           <scope>true</scope>
</dependency>
```
`<scope>true</scope>` should change to `<optional>true</optional>` ?

**Comment by lovepoem** [comment]
I think it should be `<scope>provided</scope>`

**Comment by wr1ttenyu** [comment]
> I think it should be `<scope>provided</scope>`

i think you are right.

**Comment by wr1ttenyu** [comment]
> I think it should be `<scope>provided</scope>`
i have commited pull request to correct this place and 3q for your reply.
i am a novice, if i have some thing wrong, please dont mind.

**Comment by wr1ttenyu** [comment]
> I think it should be `<scope>provided</scope>`

i have commited pull request to correct this place and 3q for your reply.
i am a novice, if i have some thing wrong, please dont mind.

**Comment by mercyblitz** [comment]
Thanks,  will be changed <optional>true</optional>
