### ISSUE TITLE
与https://github.com/alibaba/dubbo-spring-boot-starter

### ISSUE THREAD

**Issue by pangziandapple** [apache/incubator-dubbo-spring-boot-project#278]
apache集成的dubbo-spring-boot-starter和阿里巴巴集成的dubbo-spring-boot-starter有什么区别

**Comment by pangziandapple** [comment]
http://mvnrepository.com/artifact/com.alibaba.boot/dubbo-spring-boot-starter
and http://mvnrepository.com/artifact/com.alibaba.spring.boot/dubbo-spring-boot-starter

**Comment by mercyblitz** [comment]
Duplicated #279
