### ISSUE TITLE
I want to know the difference between alibaba dubbo-spring-boot-project and apache dubbo-spring-boot-project?

### ISSUE THREAD

**Issue by pangziandapple** [apache/incubator-dubbo-spring-boot-project#279]
I want to know the difference between alibaba dubbo-spring-boot-starter and apache dubbo-spring-boot-starter?

**Comment by pangziandapple** [comment]
http://mvnrepository.com/artifact/com.alibaba.boot/dubbo-spring-boot-starter
and http://mvnrepository.com/artifact/com.alibaba.spring.boot/dubbo-spring-boot-starter

**Comment by mercyblitz** [comment]
Current is official version
