### ISSUE TITLE
DemoService not found

### ISSUE THREAD

**Issue by yy755964539** [apache/incubator-dubbo-spring-boot-project#281]
tell me why,project's interface DemoService not access，i create project always exception，but clone your project don‘t error，normal start，online wait，tell me why！
![image](https://user-images.githubusercontent.com/33890981/45671777-ef3bf400-bb58-11e8-9209-becb7ada7a70.png)this me picture，

![image](https://user-images.githubusercontent.com/33890981/45671797-0844a500-bb59-11e8-86b9-95acc4b38998.png)this your project

**Comment by mercyblitz** [comment]
`@EnableDubbo` is an annotation for Spring Framework, and the current project provides auto-configure underlayer components, thus it's unnecessary to use `@EnableDubbo`.
