### ISSUE TITLE
com.alibaba.boot 你的这个包和这个是 com.alibaba.spring.boot是同一个？

### ISSUE THREAD

**Issue by godpit** [apache/incubator-dubbo-spring-boot-project#282]
com.alibaba.boot 你的这个包和这个是 com.alibaba.spring.boot是同一个？
com.alibaba.spring.boot 2.0的例子，你给出com.alibaba.boot这个版本的？

**Comment by mercyblitz** [comment]
No, com.alibaba.boot is official ~
