### ISSUE TITLE
使用springboot2.06整合dubbo时运行provider出现Failed to determine a suitable driver class

### ISSUE THREAD

**Issue by zsjzero** [apache/incubator-dubbo-spring-boot-project#293]
Description:

Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.

Reason: Failed to determine a suitable driver class

**Comment by echokk11** [comment]
same issue

**Comment by mercyblitz** [comment]
Please exclude `DataSourceAutoConfiguration` class
