### ISSUE TITLE
consumer引用提供者报NullPointerException

### ISSUE THREAD

**Issue by yufeng629** [apache/incubator-dubbo-spring-boot-project#296]
以DemoService为例，当DemoService没有任何服务提供者暴露到注册中心的时候，此时启动consumer，这时在消费者端不会生成DemoService的代理对象，导致程序运行的时候就报NullPointerException异常，我用springboot 1.5.13、dubbo 2.6.2、dubbo-starter 0.1.0、curator 4.0.1

**Comment by mercyblitz** [comment]
This issue has been fixed on 2.6.5

Please add dependencies in your Maven `pom.xml`, like this:

```xml
<!-- Dubbo -->
<dependency>
    <groupId>com.alibaba</groupId>
    <artifactId>dubbo</artifactId>
    <version>2.6.5</version>
</dependency>
<!-- Spring Context Extras -->
<dependency>
    <groupId>com.alibaba.spring</groupId>
    <artifactId>spring-context-support</artifactId>
    <version>1.0.2</version>
</dependency>
```
