### ISSUE TITLE
有没有考虑更细化注解？

### ISSUE THREAD

**Issue by a601942905git** [apache/incubator-dubbo-spring-boot-project#298]
比如我们发布一个服务需要使用@Service注解，此时会存在多个，一个是Dubbo提供的，一个是Spring提供的，我们在依赖服务的时候会使用到@Reference注解，一个是Dubbo提供的，一个是别的提供的。能否提供类似@DubboService、@DubboReference这样的呢?

**Comment by mercyblitz** [comment]
Dubbo Framework has handled duplicated `@Service` issues, thus it's unnecessary to extract annotations for same features, what's more, it brings more maintainance cost.
