### ISSUE TITLE
如何做junit provide单元测试

### ISSUE THREAD

**Issue by shuohao** [apache/incubator-dubbo-spring-boot-project#299]
我开发了一个dubbo provider，然后想junit单测作为消费者调用provider，谁有demo吗

@RunWith(SpringRunner.class)
@SpringBootTest

**Comment by mercyblitz** [comment]
Please take a look at : https://github.com/apache/incubator-dubbo/blob/master/dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/context/properties/DefaultDubboConfigBinderTest.java
