### ISSUE TITLE
yaml配置文件无法正确支持

### ISSUE THREAD

**Issue by leyou240** [apache/incubator-dubbo-spring-boot-project#30]
provider改为yaml配置之后，provider运行正常，但consumer会抛异常。并且DemoService为null。
consumer使用properties和yaml均正常。
![yaml](https://user-images.githubusercontent.com/9214525/35609457-5527285a-0698-11e8-8a42-248443fc3268.png)

**Comment by mercyblitz** [comment]
@leyou240 Please attatch configuration

**Comment by leyou240** [comment]
@mercyblitz 
[yaml.zip](https://github.com/dubbo/dubbo-spring-boot-project/files/1681405/yaml.zip)

**Comment by mercyblitz** [comment]
Your attached file is provider? please upload whole demo

**Comment by leyou240** [comment]
I just change the properties file to yaml format. The other are same as whole project.

**Comment by luffyke** [comment]
@mercyblitz this should be a bug, when using **yaml** config, the port in ProtocolConfig is set to null. and provider export the service with default netty port 20880, makes Consumer get **connection refuse** exception, this is unexpected.

ps. same config for **properties** and **yaml** file. I suggest you test yaml in your environment.

**Comment by luffyke** [comment]
```
INFO  com.alibaba.dubbo.config.AbstractConfig - [DUBBO] Export dubbo service myService to url dubbo://myip:20880/myService?anyhost=true&application=challenge-dubbo&bind.ip=myip&bind.port=20880&dubbo=2.0.1&generic=false&interface=myService&methods=sayHello&pid=24863&revision=1.0
```
above is the dubbo INFO log for yaml config.

**Comment by luffyke** [comment]
Another issue, my dubbo version is 2.5.9, but the version in output log is 2.0.1, please make sure you generate the correct **MANIFEST.MF** file, i found that the version is from this file.

**Comment by weaponready** [comment]
configuration not works while using application.yml

**Comment by lovepoem** [comment]
Duplicate with https://github.com/alibaba/dubbo/issues/1399

It is fixed in https://github.com/alibaba/dubbo/pull/1401   ，will be released in next version

**Comment by lovepoem** [comment]
Now https://github.com/alibaba/dubbo/milestone/13 is released.   dubbo 2.6.1 has fixed this bug
