### ISSUE TITLE
如何添加多个注册中心？

### ISSUE THREAD

**Issue by Killua67** [apache/incubator-dubbo-spring-boot-project#301]
单个 是这个dubbo.registry.address=zookeeper://10.10.10.10:2181
多个呢

**Comment by zonghaishang** [comment]
http://dubbo.apache.org/zh-cn/docs/user/references/registry/zookeeper.html

**Comment by hylitjob** [comment]
@zonghaishang 请教， 多注册中心老版本是通过xml配置来实现，注解方式怎么实现多注册中心呢，只通过属性文件配置多注册中心
