### ISSUE TITLE
包扫描路径写成dubbo.scan.base-packages时，无法暴露服务

### ISSUE THREAD

**Issue by jaychang9** [apache/incubator-dubbo-spring-boot-project#302]
在application.properties配置文件中，将扫描包路径写成dubbo.scan.base-packages时候，服务是没法暴露的。必须写成dubbo.scan.basePackages才可以

**Comment by wangenlu** [comment]
@ConditionalOnProperty(
        name = {"dubbo.scan.basePackages"}
    )
    @ConditionalOnClass({ConfigurationPropertySources.class})
    @Bean
    public ServiceAnnotationBeanPostProcessor serviceAnnotationBeanPostProcessor(Environment environment) {
        Set<String> packagesToScan = (Set)environment.getProperty("dubbo.scan.basePackages", Set.class, Collections.emptySet());
        return new ServiceAnnotationBeanPostProcessor(packagesToScan);
    }




但是在{
      "sourceType": "com.alibaba.boot.dubbo.autoconfigure.DubboScanProperties",
      "name": "dubbo.scan.base-packages",
      "description": "The basePackages to scan , the multiple-value is delimited by comma\n\n @see EnableDubbo#scanBasePackages()",
      "type": "java.util.Set<java.lang.String>"
    }
造成自动提示dubbo.scan.base-packages  导致dubbo.scan.basePackages 获取不到，希望能及早更新一下吧，这个稍不留神就容易出错

**Comment by nswish** [comment]
有用！

**Comment by mercyblitz** [comment]
Thanks for your report, this merged PR will resolve this issue : https://github.com/apache/incubator-dubbo-spring-boot-project/pull/233
