### ISSUE TITLE
现阶段是否支持hessian等其他协议？

### ISSUE THREAD

**Issue by sinelu** [apache/incubator-dubbo-spring-boot-project#312]
尝试如下修改了配置：

<pre>dubbo:
  protocol:
    id: hessian
    name: hessian
    port: 22426
    status: server</pre>

启动时候可以看见日志：
<pre>[DUBBO] Register dubbo service com.demo.service.IService url hessian://xxxxxxx</pre>
似乎是成功通过hessian协议注册暴露了服务

但后续日志即为：
<pre>[DUBBO] Run shutdown hook now., dubbo version: 2.6.2, current host: 172.16.1.195 [DubboShutdownHook] (com.alibaba.dubbo.config.AbstractConfig) (AbstractConfig.java:81) 

[DUBBO] Close all registries [], dubbo version: 2.6.2, current host: 172.16.1.195 [DubboShutdownHook] (com.alibaba.dubbo.registry.support.AbstractRegistryFactory) (AbstractRegistryFactory.java:64) 

[DUBBO] Unexport service: injvm://127.0.0.1/com.demo.service.IService?anyhost=true&application=object-storage-engine-provider&bind.ip=172.16.1.195&bind.port=22426&dubbo=2.6.2&generic=false&interface=com.demo.service.IService&methods=saveFileManual,saveFile,saveFileToPath,saveImage&pid=5008&side=provider&status=server&timestamp=1543221290955, dubbo version: 2.6.2, current host: 172.16.1.195 [DubboShutdownHook] (com.alibaba.dubbo.rpc.protocol.injvm.InjvmProtocol) (AbstractProtocol.java:76) </pre>

随后spring boot项目停止运行，无报错无warning

dubbo-spring-boot-starter版本为0.2.0
com.caucho.hessian版本为4.0.51

**Comment by mercyblitz** [comment]
Please add  Dubbo 2.6.5  in order to override indirectly dependencies.
