### ISSUE TITLE
[Notification] Dubbo Spring Boot Project Update

### ISSUE THREAD

**Issue by mercyblitz** [apache/incubator-dubbo-spring-boot-project#317]
Hi, community,

  I'm very sorry about the delayed update of Dubbo Spring Boot Project, and a new update will be released using Dubbo `2.6.5` in next or two week.

**Comment by KeRan213539** [comment]
:+1::+1::+1:

**Comment by mercyblitz** [comment]
If you add  Dubbo 2.6.5  to override indirectly dependencies:
```xml
<dependency>
    <groupId>com.alibaba</groupId>
    <artifactId>dubbo</artifactId>
    <version>2.6.5</version>
</dependency>
```

The most issues will be fixed.

**Comment by zghkm** [comment]
👍👍👍

**Comment by maoling** [comment]
ping @mercyblitz 
could you plz step into this [issue](https://github.com/openzipkin/sleuth-webmvc-example/issues/20)?

**Comment by lhzsdnu** [comment]
大约什么时候会发布正式版本

**Comment by mercyblitz** [comment]
@lhzsdnu 1.0.0 will be released after Dubbo `2.7.0`, at that time, the Maven GAV and package will be redefined, and next release will focus on the bugfix.

**Comment by mercyblitz** [comment]
`0.2.1-SNAPSHOT` has been released.

**Comment by KeRan213539** [comment]
快照:scream::joy:
