### ISSUE TITLE
default dubbo.application.name to spring.application.name

### ISSUE THREAD

**Issue by adriancole** [apache/incubator-dubbo-spring-boot-project#321]
It feels like extra work to redundantly add dubbo.application.name as same as spring.application.name. I didn't have to do this in the other dubbo plugin. Can you please default it to the spring name?

Extra work makes dubbo feel cluttered, and we want dubbo to feel easy as possible.

```java
  public static void main(String[] args) {
    SpringApplication.run(Backend.class,
        "--spring.application.name=backend",
        // Dubbo does not inherit the application name, so you have to repeat it
        "--dubbo.application.name=backend",
--snip--
```

**Comment by mercyblitz** [comment]
Ok, it's reasonable.
