### ISSUE TITLE
NoClassDefFoundError:com/alibaba/dubbo/config/spring/util/PropertySourcesUtils

### ISSUE THREAD

**Issue by SamuelTao** [apache/incubator-dubbo-spring-boot-project#326]
引入包：
     
```
<dependency>
            <groupId>com.alibaba.boot</groupId>
            <artifactId>dubbo-spring-boot-starter</artifactId>
            <version>0.1.1</version>
        </dependency>
        <!-- Dubbo -->
        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>dubbo</artifactId>
            <version>2.6.5</version>
        </dependency>
        <!-- Spring Context Extras -->
        <dependency>
            <groupId>com.alibaba.spring</groupId>
            <artifactId>spring-context-support</artifactId>
            <version>1.0.2</version>
        </dependency>
```

报错如下：
` Error creating bean with name 'com.alibaba.dubbo.config.ApplicationConfig#0': Initialization of bean failed; nested exception is java.lang.NoClassDefFoundError: com/alibaba/dubbo/config/spring/util/PropertySourcesUtils`

**Comment by mercyblitz** [comment]
Did you put `com.alibaba.spring:spring-context-support` into <dependencies>?  It does not work on <dependenciesManagement>.

**Comment by SamuelTao** [comment]
java.lang.NoClassDefFoundError: com/alibaba/dubbo/config/spring/util/PropertySourcesUtils
并不在这个包里面
![image](https://user-images.githubusercontent.com/10590925/51305331-85cfe180-1a75-11e9-8730-2dfa69fe009f.png)

**Comment by mercyblitz** [comment]
Plead update starter
