### ISSUE TITLE
dubbo-spring-boot-sample-consumer 配置问题

### ISSUE THREAD

**Issue by hudepin** [apache/incubator-dubbo-spring-boot-project#335]
DemoConsumerController 的@Reference(
            version = "${demo.service.version}",
            url = "dubbo://localhost:12345")  demo.service.version 给了0.0.0 然后在http://localhost:8080/sayHello?name=HelloWorld 的时候会找不到服务

**Comment by mercyblitz** [comment]
What's the error message? My side work.

**Comment by hudepin** [comment]
1、java.lang.NoClassDefFoundError: javax/servlet/http/HttpServlet，Servlet dependency scope need set rumtime
2、when set Servlet api runtime ,cousumer and provider can start up sucess ,when I access test url :http://localhost:8080/sayHello?name=HelloWorld, then ocur some exception,
consumer exception log：
com.alibaba.dubbo.remoting.RemotingException: Not found exported service: com.alibaba.boot.dubbo.demo.consumer.DemoService:12345 in [com.alibaba.boot.dubbo.demo.consumer.DemoService:1.0.0:12345], may be version or group mismatch , channel: consumer: /192.168.56.1:4358 --> provider: /192.168.56.1:12345, message:RpcInvocation [methodName=sayHello, parameterTypes=[class java.lang.String], arguments=[HelloWorld], attachments={path=com.alibaba.boot.dubbo.demo.consumer.DemoService, input=248, dubbo=2.0.2, interface=com.alibaba.boot.dubbo.demo.consumer.DemoService, version=0.0.0}]
	at com.alibaba.dubbo.rpc.protocol.dubbo.DubboProtocol.getInvoker(DubboProtocol.java:213)
provider exception log:
com.alibaba.dubbo.remoting.RemotingException: Not found exported service: com.alibaba.boot.dubbo.demo.consumer.DemoService:12345 in [com.alibaba.boot.dubbo.demo.consumer.DemoService:1.0.0:12345], may be version or group mismatch , channel: consumer: /192.168.56.1:4358 --> provider: /192.168.56.1:12345, message:RpcInvocation [methodName=sayHello, parameterTypes=[class java.lang.String], arguments=null, attachments={path=com.alibaba.boot.dubbo.demo.consumer.DemoService, dubbo=2.0.2, interface=com.alibaba.boot.dubbo.demo.consumer.DemoService, version=0.0.0}]
	at com.alibaba.dubbo.rpc.protocol.dubbo.DubboProtocol.getInvoker(DubboProtocol.java:213) ~[dubbo-2.6.5.jar:2.6.5]

3，I doubt some code forget to commit to respository ？ and My IDE is Ideal ,thx

**Comment by hudepin** [comment]
![image](https://user-images.githubusercontent.com/4598520/50265483-d514f900-045a-11e9-9524-03c154e57bc6.png)
I view git commit log and found demo.service.version = 1.0.0 forget copy to application.yml?

**Comment by mercyblitz** [comment]
@hudepin Yes, I forgot, you could pull  a request for this project :D

**Comment by mercyblitz** [comment]
@hudepin However, this property is not required.

**Comment by mercyblitz** [comment]
@hudepin fixed, please see https://github.com/apache/incubator-dubbo-spring-boot-project/pull/337

**Comment by alvindaiyan** [comment]
I followed the code, but the service version sent from the consumer is always 0.0.0. I doubt there maybe a bug in Dubbo. my Dubbo version is 2.7.3

**Comment by xu2519** [comment]
> I followed the code, but the service version sent from the consumer is always 0.0.0. I doubt there maybe a bug in Dubbo. my Dubbo version is 2.7.3

me too

**Comment by xu2519** [comment]
i invoke my local dubbo service,old version works well.

**Comment by xu2519** [comment]
> > I followed the code, but the service version sent from the consumer is always 0.0.0. I doubt there maybe a bug in Dubbo. my Dubbo version is 2.7.3
> 
> me too

i invoke my local dubbo service,old version works well.

**Comment by alvindaiyan** [comment]
> > > I followed the code, but the service version sent from the consumer is always 0.0.0. I doubt there maybe a bug in Dubbo. my Dubbo version is 2.7.3
> > 
> > 
> > me too
> 
> i invoke my local dubbo service,old version works well.

Correct, to make it work. I've to revert to older version
