### ISSUE TITLE
dubbo 升级2.6.5  RelaxedDubboConfigBinder引用的是com.alibaba.dubbo.config.spring.util包

### ISSUE THREAD

**Issue by Dron1sh** [apache/incubator-dubbo-spring-boot-project#336]
![image](https://user-images.githubusercontent.com/9458105/50272307-4b712580-0472-11e9-9b43-d723c914c969.png)
com.alibaba.spring:spring-context-support 1.0.2版本的PropertySourcesUtils 在包com.alibaba.spring.util下

**Comment by mercyblitz** [comment]
Correct, so you should add an extra Maven dependency:
```xml
<!-- Spring Context Extras -->
<dependency>
    <groupId>com.alibaba.spring</groupId>
    <artifactId>spring-context-support</artifactId>
    <version>1.0.2</version>
</dependency>
```

**Comment by Dron1sh** [comment]
> Correct, so you should add an extra Maven dependency:
> 
> ```
> 
> <dependency>
>     <groupId>com.alibaba.spring</groupId>
>     <artifactId>spring-context-support</artifactId>
>     <version>1.0.2</version>
> </dependency>
> ```

I have import spring-context-support, but `PropertySourcesUtils` located in package `com.alibaba.spring.util`,  `RelaxedDubboConfigBinder` import class `PropertySourcesUtils` is located in package `com.alibaba.dubbo.config.spring.util`, that's not
match
![image](https://user-images.githubusercontent.com/9458105/50321966-32b64d80-050e-11e9-908a-dad2ad00cac7.png)

**Comment by huangyoje** [comment]
I think the problem is not  resolved. 

The RelaxedDubboConfigBinder(version 0.1.1) use `com.alibaba.<font color=red>dubbo.config</font>.spring.util.PropertySourcesUtils` , while spring-context-support(version 1.0.2) has `com.alibaba.spring.util.PropertySourcesUtils`

@mercyblitz

**Comment by Dron1sh** [comment]
> I think the problem is not resolved.
> 
> The RelaxedDubboConfigBinder(version 0.1.1) use `com.alibaba.**dubbo.config**.spring.util.PropertySourcesUtils` , while spring-context-support(version 1.0.2) has `com.alibaba.spring.util.PropertySourcesUtils`
> 
> @mercyblitz

I have create same package in my project to resolve it -.-

**Comment by huangyoje** [comment]
> I have create same package in my project to resolve it -.-

good for you.  I wonder why this issue is closed?  Is there anything we don't know? or we use it incorrectly?

**Comment by Dron1sh** [comment]
> > I have create same package in my project to resolve it -.-
> 
> good for you. I wonder why this issue is closed? Is there anything we don't know? or we use it incorrectly?

not clear, but i found  same issue in past;
 maybe project not springboot is ok.
`AbstractDubboConfigBinder` another subclass `DefaultDubboConfigBinder` 
import com.alibaba.dubbo.config.spring.util.PropertySourcesUtils  is right

**Comment by Dron1sh** [comment]
> > I have create same package in my project to resolve it -.-
> 
> good for you. I wonder why this issue is closed? Is there anything we don't know? or we use it incorrectly?

not clear, I found same issue in past;
maybe project isn't springboot is ok.
`AbstractDubboConfigBinder` another subclass 
``` java
import com.alibaba.spring.util.PropertySourcesUtils;
import java.util.Map;
import org.springframework.beans.MutablePropertyValues;
import org.springframework.validation.DataBinder;

public class DefaultDubboConfigBinder extends AbstractDubboConfigBinder {
```
dubbo version is 2.6.5
