### ISSUE TITLE
sameples下的样例工程注册中心改为nacos后服务发现失败

### ISSUE THREAD

**Issue by wzlee** [apache/incubator-dubbo-spring-boot-project#338]
修改provider的配置信息：
![image](https://user-images.githubusercontent.com/4182865/50337290-97dc6400-054b-11e9-9e86-aa07c937dc4e.png)
服务注册成功：
![image](https://user-images.githubusercontent.com/4182865/50337308-a88cda00-054b-11e9-85e6-490df1107195.png)
修改consumer的配置信息：
![image](https://user-images.githubusercontent.com/4182865/50337505-4ed8df80-054c-11e9-83ff-a96c89ae51e4.png)
启动consumer提示异常：
![image](https://user-images.githubusercontent.com/4182865/50337539-6617cd00-054c-11e9-827f-3bb8e5c18692.png)

**Comment by mercyblitz** [comment]
Please update the sample code
