### ISSUE TITLE
consumer start exception

### ISSUE THREAD

**Issue by wtthard** [apache/incubator-dubbo-spring-boot-project#341]
***************************
APPLICATION FAILED TO START
***************************

Description:

Configuration property name 'management.endpoint.dubboConfigs.cache.time-to-live' is not valid:

    Invalid characters: 'C'
    Bean: jmxMBeanExporter
    Reason: Canonical names should be kebab-case ('-' separated), lowercase alpha-numeric characters and must start with a letter

Action:

Modify 'management.endpoint.dubboConfigs.cache.time-to-live' so that it conforms to the canonical names requirements.

**Comment by mercyblitz** [comment]
Thanks for your report, it will be fixed.
