### ISSUE TITLE
注册多group问题

### ISSUE THREAD

**Issue by cwdtom** [apache/incubator-dubbo-spring-boot-project#349]
项目中需要用到在同一个注册中心上同时注册多个group，我尝试了下，发现貌似在配置文件里面用逗号的形式配多个group是不行的，想问一下现在的版本是否支持。
我用的是0.1.1的starter版本

**Comment by cwdtom** [comment]
@EnableDubboConfig(multiple = true)

dubbo.registrys.local.group=local
dubbo.registrys.test.group=test
dubbo.registry.local.address=zookeeper://xxxx:2181
dubbo.registry.test.address=zookeeper://xxxx:2181

这样配置可以实现吗？

**Comment by cwdtom** [comment]
实验了下貌似这样是可以成功的。。。希望官方可以把文档和wiki做的好一点，如果的确是我上面的配置解决，那请帮忙关闭这个issue

**Comment by mercyblitz** [comment]
Ok, We are working on the document.
