### ISSUE TITLE
curator-framework 版本低，项目运行不起来

### ISSUE THREAD

**Issue by lhzsdnu** [apache/incubator-dubbo-spring-boot-project#350]
测试最新版本 curator-framework如果用2.12.0,项目运行会报错，换成最新版本2.13.0，项目正常运行。

**Comment by mercyblitz** [comment]
It's works ,please take a look at https://github.com/apache/incubator-dubbo-spring-boot-project/tree/master/dubbo-spring-boot-samples/dubbo-registry-zookeeper-samples
