### ISSUE TITLE
What time the 0.2.1 will be release ?

### ISSUE THREAD

**Issue by sarins** [apache/incubator-dubbo-spring-boot-project#351]
@mercyblitz

**Comment by mercyblitz** [comment]
This week will start a community vote, please wait for a while :D

**Comment by ralf0131** [comment]
Please subscribe to the mailing list to get the latest status, the vote has been on going there.

How to subscribe: http://dubbo.apache.org/zh-cn/docs/developers/contributor-guide/mailing-list-subscription-guide_dev.html

**Comment by mercyblitz** [comment]
Released~
