### ISSUE TITLE
当提供者未启动时，Reference引用为空问题

### ISSUE THREAD

**Issue by loveychao** [apache/incubator-dubbo-spring-boot-project#353]
异常情况：
1、当提供者未启动时，@Reference引用对象为空值
2、当提供者上线后，@Reference引用对象仍然为空
提示：
1、当提供者启动时启动消费者，能正常引用到服务
2、使用xml配置方式，消费者不存在时@Reference引用不为空

**Comment by mercyblitz** [comment]
@cookerzhu 
Please wait for a new release, it will be released in this week.
