### ISSUE TITLE
入门demo有问题  跑不起来

### ISSUE THREAD

**Issue by xulingfeng931027** [apache/incubator-dubbo-spring-boot-project#392]
在springboot的启动类应该加上@EnableDubbo  否则访问时会报500 空指针异常,,找了很久资料才发现!!!

**Comment by biyuhao** [comment]
@xulingfeng931027 方面附上更多信息么，我没能重现。比如使用的分支/版本、运行的哪个demo、错误堆栈等，可以方便一起诊断问题。

**Comment by xulingfeng931027** [comment]
> @xulingfeng931027 方面附上更多信息么，我没能重现。比如使用的分支/版本、运行的哪个demo、错误堆栈等，可以方便一起诊断问题。

https://github.com/xulingfeng931027/springboot-dubbo
这是我的代码,完全按照这个demo示例做的,只是在启动类上多加了一个@EnableDubbo的注解,不加的话consumer访问时无法连接到provider

**Comment by mercyblitz** [comment]
Please refer to the latest samples.
