### ISSUE TITLE
无法获取到apollo配置中心的配置项

### ISSUE THREAD

**Issue by hanwangkun** [apache/incubator-dubbo-spring-boot-project#40]
现在项目中用到了apollo配置中心，但是发现它无法从配置中心拉取dubbo配置项，正在阅读代码！

**Comment by mercyblitz** [comment]
具体错误是什么？

**Comment by nobodyiam** [comment]
@hanwangkun @mercyblitz 

I added a demo project showing dubbo-spring-boot-project 0.2.0 works with apollo now.

The demo project could be found in https://github.com/ctripcorp/apollo-use-cases
