### ISSUE TITLE
通过@Reference方式注入服务没有在Spring的容器中

### ISSUE THREAD

**Issue by shelltea** [apache/incubator-dubbo-spring-boot-project#400]
版本：0.2.0

通过`@Reference`方式注入服务，通过applicationContext.getBean无法获取，提示：org.springframework.beans.factory.NoSuchBeanDefinitionException

代码：

```
    @Reference
    private UserService userService;
    @Autowired
    private ApplicationContext applicationContext;
   
    ....


    LOGGER.debug("{}", applicationContext.getBean(UserService.class));
```

输出：

```
org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.xxx.service.UserService' available
```

尝试了 #217 中提供的方式，依然无效。

**Comment by amit-gshe** [comment]
#232 also referenced this issue.

**Comment by mercyblitz** [comment]
It's not a bug, because `@Reference` does not enhancement inject object as a Spring Bean, that's why `BeanFactory` can't retrieve them by type.

**Comment by amit-gshe** [comment]
Is there a way to construct a `@Reference` bean defination manaually in spring boot fashion?

**Comment by amit-gshe** [comment]
I did try this way but I did not find an existing property class I can use to define a spring bean for `ReferenceBean`.  Could you please demonstrate how to define a `@ReferenceBean` manaually?

**Comment by mercyblitz** [comment]
```java
@Bean
public  ReferenceBean<YourBean> yourBean(){
  ReferenceBean<YourBean>  yourBean = new ReferenceBean<YourBean>();
  ...
  reutrn yourBean;
}
```

more details please refer this document: http://dubbo.apache.org/zh-cn/docs/user/configuration/api.html
