### ISSUE TITLE
duubo自定义配置文件所在目录问题

### ISSUE THREAD

**Issue by wangruyu1** [apache/incubator-dubbo-spring-boot-project#401]
boot:2.1.1 dubbo:2.6.2 (2.6.5有问题)
由于外部tomcat使用dubbo客户端,配置文件多，需要分目录放。

我的配置:
spring:
  config:
    location: 
    - classpath:/ #这是boot的默认配置目录
    - classpath:/config/ #这是boot的默认配置目录
    - classpath:/dubbo/ #这是自定义配置目录
  profiles:
    include: 
    - dubbo-common
    - dubbo-zoo
    - dubbo-application
    - dubbo-protocol
    - dubbo-referer
现在我把application-dubbo-referer.properties等文件放到config/一切正常,放到dubbo/报错(原因就是没加载这些配置文件).
其中application-dubbo-referer.properties内容：
#接口超时时间
dubbo.reference.timeout = 10000
#长连接数量
dubbo.reference.connections = 10

这个是否是dubbo的问题呢？谢谢

**Comment by mercyblitz** [comment]
No Problem If Spring Environment can locate those properties.
