### ISSUE TITLE
Remove src/main/resources/META-INF/spring.provides file from starter module

### ISSUE THREAD

**Issue by zhiwsun** [apache/incubator-dubbo-spring-boot-project#403]
[Remove spring.provides files](https://github.com/spring-projects/spring-boot/issues/12435)

It's unnecessary to keep spring.providers file in starter module since it is only used in STS IDE. 
From the SpringBoot team, starter module would be just keep a single pom.xml file.

**Comment by mercyblitz** [comment]
Thanks, it will be removed at 1.0.0 release.
