### ISSUE TITLE
[Notification] Apache Dubbo(Incubator) Spring Boot 0.2.1 and 0.1.2 are available

### ISSUE THREAD

**Issue by mercyblitz** [apache/incubator-dubbo-spring-boot-project#416]
Hello Dubbo Community,

I'm glad to announce that Apache Dubbo(Incubator) Spring Boot 0.2.1 and 0.1.2  have been released and are now available from Maven Central.  

Release Notes:
0.2.1: https://github.com/apache/incubator-dubbo-spring-boot-project/releases/tag/0.2.1
0.1.2: https://github.com/apache/incubator-dubbo-spring-boot-project/releases/tag/0.1.2

If you have trouble with Dubbo Spring Boot, please discuss with Dubbo community at issues.

**Comment by zhiwsun** [comment]
Congratulations 🎉🎉🎉

**Comment by yinwerhong** [comment]
@mercyblitz 指了sonatype-nexus-snapshots和sonatype-nexus-releases都报错
Failed to collect dependencies at com.alibaba.boot:dubbo-spring-boot-starter:jar:0.2.1: Failed to read artifact descriptor for com.alibaba.boot:dubbo-spring-boot-starter:jar:0.2.1: Could not find artifact com.alibaba.boot:dubbo-spring-boot-parent:pom:${revision} in central (https://repo.maven.apache.org/maven2) -> [Help 1]

**Comment by shelltea** [comment]
同样的问题：
Failed to read artifact descriptor for com.alibaba.boot:dubbo-spring-boot-starter:jar:0.2.1

**Comment by shinvi** [comment]
同样的问题：
Failed to read artifact descriptor for com.alibaba.boot:dubbo-spring-boot-starter:jar:0.2.1

**Comment by mercyblitz** [comment]
Please use 
```xml
    <!-- Dubbo Spring Boot Starter -->
    <dependency>
        <groupId>com.alibaba.boot</groupId>
        <artifactId>dubbo-spring-boot-autoconfigure</artifactId>
        <version>0.2.1</version>
    </dependency>
```

**Comment by yinwerhong** [comment]
@mercyblitz 仍旧是这个问题
Failed to collect dependencies at com.alibaba.boot:dubbo-spring-boot-autoconfigure:jar:0.2.1: Failed to read artifact descriptor for com.alibaba.boot:dubbo-spring-boot-autoconfigure:jar:0.2.1: Could not transfer artifact com.alibaba.boot:dubbo-spring-boot-parent:pom:${revision} from/to nexus-aliyun-repo (http://maven.aliyun.com/nexus/content/groups/public): TransferFailedException: ClientProtocolException: Invalid redirect URI: https://maven.aliyun.com/nexus/content/groups/public/com/alibaba/boot/dubbo-spring-boot-parent/${revision}/dubbo-spring-boot-parent-${revision}.pom: Illegal character in path at index 96: https://maven.aliyun.com/nexus/content/groups/public/com/alibaba/boot/dubbo-spring-boot-parent/${revision}/dubbo-spring-boot-parent-${revision}.pom -> [Help 1]

**Comment by mercyblitz** [comment]
@yinwerhong Thanks to your report, I'm considering re-upload it.

**Comment by zxf527** [comment]
> Thanks to your report, I'm considering re-upload it.

上传完成麻烦回复下

**Comment by mercyblitz** [comment]
@zxf527 No problem, it's working in the process.

**Comment by silvergray** [comment]
等待....

**Comment by mercyblitz** [comment]
Please update the latest one for Spring Boot 2.x: 

```xml
    <dependency>
        <groupId>com.alibaba.boot</groupId>
        <artifactId>dubbo-spring-boot-starter</artifactId>
        <version>0.2.1.RELEASE</version>
    </dependency>
```

Or for Spring 1.x:

```
```

**Comment by zhengqigo** [comment]
Turned ok now.

**Comment by choaryzhang** [comment]
compile group: 'com.alibaba.boot', name: 'dubbo-spring-boot-starter', version: '0.2.1.RELEASE'
不能直接获取到 dubbo 2.6.5的jar。
请确保maven仓库中的dependency 是否正确

**Comment by mercyblitz** [comment]
@choaryzhang It's an optional dependency.

**Comment by VancySavoki** [comment]
@mercyblitz Hi, In 0.2.1.RELEASE, 
commit https://github.com/apache/dubbo-spring-boot-project/commit/24ce1aeaee08da469c045cbf39ef036bf7cac815 were not merged, is there any special reason please?
