### ISSUE TITLE
0.2.1.RELEASE dubbo rest protocol not support tomcat 9 

### ISSUE THREAD

**Issue by sylartp** [apache/incubator-dubbo-spring-boot-project#424]
since spring boot 2.1.0 tomcat-embed upgrade 9.
i tried to use dubbo rest protocol and when i failed to startup my spring boot application on spring boot 2.1.2.RELEASE so i have to downgrade tomcat version 
add this property in pom <tomcat.version>8.5.34</tomcat.version>

the error info is as below.

2019-01-30 11:52:18.281 ERROR 26741 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call the method org.apache.catalina.connector.Connector.setProtocol(Ljava/lang/String;)V but it does not exist. Its class, org.apache.catalina.connector.Connector, is available from the following locations:

    jar:file:/Users/tppppp/Documents/Maven-Repository/org/apache/tomcat/embed/tomcat-embed-core/9.0.14/tomcat-embed-core-9.0.14.jar!/org/apache/catalina/connector/Connector.class

It was loaded from the following location:

    file:/Users/tppppp/Documents/Maven-Repository/org/apache/tomcat/embed/tomcat-embed-core/9.0.14/tomcat-embed-core-9.0.14.jar

Action:

Correct the classpath of your application so that it contains a single, compatible version of org.apache.catalina.connector.Connector

**Comment by mercyblitz** [comment]
You could switch rest's server to be Netty, for example:

```properties
dubbo.protocols.rest.name=rest
dubbo.protocols.rest.server=netty
```

**Comment by mercyblitz** [comment]
It will be fixed after Dubbo 2.6.5

**Comment by sylartp** [comment]
@mercyblitz  
Unfortunately，i tried your suggestion. But it still failed the same error info. anyway, downgrading tomcat version seems to be the only way so far.  thanks for your help and notice.

**Comment by zondahuman** [comment]
> It works in Dubbo 2.7+

it do not work in Dubbo 2.7.1 or 2.7.2

**Comment by cxplan** [comment]
> > It works in Dubbo 2.7+
> 
> it do not work in Dubbo 2.7.1 or 2.7.2

This problem exists in version 2.7.1, please confirm it.

**Comment by zondahuman** [comment]
> It works in Dubbo 2.7+

the problem still exists in 2.7.3, when the team fix it ?

**Comment by MrEric125** [comment]
the problem still exists in dubbo version 2.7.3 and spirng boot version 2.1.6

**Comment by MrEric125** [comment]
> 
> 
> > It works in Dubbo 2.7+
> 
> the problem still exists in 2.7.3, when the team fix it ?
 maybe U tomcat version is not right，you can choose tomcat version in spring boot
