### ISSUE TITLE
NoClassDefFoundError: com/alibaba/dubbo/common/Version

### ISSUE THREAD

**Issue by zhengqigo** [apache/incubator-dubbo-spring-boot-project#425]
Dubbo: 2.7.0
Starter: 0.2.1.RELEASE

Caused by: java.lang.ClassNotFoundException: com.alibaba.dubbo.common.Version

**Comment by yulianzhilan** [comment]
due to com.alibaba.boot.dubbo.context.event.WelcomeLogoApplicationListener imported org.apache.dubbo.common.Version; while this class does not exists in dubbo:2.7.0

**Comment by yulianzhilan** [comment]
Actually, I found the this starter isn't suitable for Dubbo 2.7.0.  Waiting for 1.0.0 release version.

**Comment by jiuchongxiao** [comment]
i have the same problem

**Comment by mercyblitz** [comment]
It's not an issue, please use 2.7.0 starter

**Comment by mark988** [comment]
pom.xml 怎么添加使用2.7.0？
