### ISSUE TITLE
java.lang.NoClassDefFoundError: org/apache/curator/RetryPolicy

### ISSUE THREAD

**Issue by 437407817** [apache/incubator-dubbo-spring-boot-project#438]
i introduce  configuration to my pom.xml of springboot which is Released version you provided ,but it shows errors like this;

java.lang.NoClassDefFoundError: org/apache/curator/RetryPolicy
	at com.alibaba.dubbo.remoting.zookeeper.curator.CuratorZookeeperTransporter.connect(CuratorZookeeperTransporter.java:27) ~[dubbo-2.6.5.jar:2.6.5]
.....

**Comment by tzxylao** [comment]
How solver

**Comment by NightFarmer** [comment]
How solver
