### ISSUE TITLE
png files in the directory

### ISSUE THREAD

**Issue by WillemJiang** [apache/incubator-dubbo-spring-boot-project#440]
There are two png files(config-popup-window.png, mconfig-popup-window.png) in the project directory.  I just checked the README.md, there is no reference of these files.
Please remove them if they are not needed.

**Comment by biyuhao** [comment]
I'm afraid it's used in `dubbo-spring-boot-autoconfigure/README.md`

`https://github.com/apache/incubator-dubbo-spring-boot-project/blob/d2b85e0a0aabcf950ff3715e46c05e08523303a1/dubbo-spring-boot-autoconfigure/README.md#L216`

**Comment by WillemJiang** [comment]
If it is used in the dubbo-spring-boot-autoconfigure, we may consider to move the png files into that directory.

**Comment by biyuhao** [comment]
sounds reasonable, thanks it's fixed
