### ISSUE TITLE
单词拼写有误 

### ISSUE THREAD

**Issue by shaoyifan** [apache/incubator-dubbo-spring-boot-project#444]
![6c4e5e84-70bb-4d02-9546-f50263f7db3e](https://user-images.githubusercontent.com/18544056/52843622-a440ff80-313d-11e9-8bc5-a6318ac9a893.png)

**Comment by kexianjun** [comment]
@shaoyifan  Can you commit a pr to fix this?

**Comment by kexianjun** [comment]
closed, since it is fixed #445
