### ISSUE TITLE
请问0.2.x如果要使用nacos配置中心需要配置两次能解决么

### ISSUE THREAD

**Issue by maojx0630** [apache/incubator-dubbo-spring-boot-project#450]
dubbo.registry.address=nacos://127.0.0.1:8848
spring.cloud.nacos.config.server-addr=127.0.0.1:8848

请问这种情况下可以合并么

**Comment by mercyblitz** [comment]
Good idea, It will be resolved in Dubbo Spring Cloud that releases soon.

**Comment by mercyblitz** [comment]
Please reference to Dubbo Spring Cloud, this feature has been supported:

https://github.com/spring-cloud-incubator/spring-cloud-alibaba/tree/master/spring-cloud-alibaba-examples/spring-cloud-alibaba-dubbo-examples
