### ISSUE TITLE
dubbo.metadata-report.address propertie description not provided

### ISSUE THREAD

**Issue by ettingshausen** [apache/incubator-dubbo-spring-boot-project#458]
Hi there!
When I use `incubator-dubbo-ops` , nothing display at `MetaData` like #212  .
According to the [configuration specification](http://dubbo.apache.org/zh-cn/blog/dubbo-admin.html), there should have a property  `incubator-dubbo-ops` but can't find in the `spring-configuration-metadata.json`
>```
># /dubbo/config/dubbo/dubbo.properties
>dubbo.registry.address=zookeeper://127.0.0.1:2181
>dubbo.metadata-report.address=zookeeper://127.0.0.1:2181
```

**Comment by mercyblitz** [comment]
Could you pull a request for it?
