### ISSUE TITLE
dubbo使用nacos作为注册中心，dubbo.registry.group，服务分组不生效

### ISSUE THREAD

**Issue by WYongLin** [apache/incubator-dubbo-spring-boot-project#460]
问下，dubbo使用nacos作为注册中心，dubbo.registry.group，服务分组是不是不生效了？这个问题怎么解决的？registry不能分组，dubbo.registry.group配置了没什么用。而且在nacos里也看不到对应的group信息。

**Comment by mercyblitz** [comment]
For now, Nacos client still does not support switching namespace via API, thus, `dubbo.registry.group` does not work in current implementation.

**Comment by mercyblitz** [comment]
It may be supported in the future.
