### ISSUE TITLE
admin中dubbo版本显示问题

### ISSUE THREAD

**Issue by qianhen-hf** [apache/incubator-dubbo-spring-boot-project#466]
registry:zookeeper://192.168.6.70:2181/com.alibaba.dubbo.registry.RegistryService?application=marketing&backup=192.168.6.71:2181,192.168.6.72:2181&dubbo=2.0.2&group=orderCenter1&interface=com.alibaba.dubbo.registry.RegistryService&pid=13780&timestamp=1552534198131, dubbo version: 2.6.5, current host: 192.168.8.153
其中 dubbo 参数为2.02这是为什么呢， 我用的2.6.5版本的dubbo
不用dubbo-spring-boot-starter 用其他方式整合的2.6.0 显示出来都是 dubbo=2.6.0

**Comment by mercyblitz** [comment]
`dubbo=2.0.2` parameter means Dubbo Communication protocol version, there was a mistake on `dubbo=2.6.0` in the legacy version.

**Comment by qianhen-hf** [comment]
oh，i see  ，thanks
