### ISSUE TITLE
 invalid stream header: 77020101

### ISSUE THREAD

**Issue by qianhen-hf** [apache/incubator-dubbo-spring-boot-project#469]
com.alibaba.dubbo.rpc.RpcException: Failed to invoke the method checkToken in the service com.ykx.userCenter.provider.api.IUserService. Tried 1 times of the providers [192.168.7.96:20889] (1/1) from the registry 192.168.6.70:2181 on the consumer 192.168.8.153 using the dubbo version 2.6.5. Last error is: Failed to invoke remote method: checkToken, provider: dubbo://192.168.7.96:20889/com.ykx.userCenter.provider.api.IUserService?anyhost=true&application=marketing&check=false&default.retries=0&default.service.filter=dubboLogFilter&dubbo=2.6.0&generic=false&interface=com.ykx.userCenter.provider.api.IUserService&methods=getSid,listPageUsers,listPageUsersNew,removeUser,unbindUserLoginName,findUserById,resetUserLoginPwd,findUserByIdNew,checkToken&pid=10736&register.ip=192.168.8.153&remote.timestamp=1552013417452&retries=0&revision=1.0.0-SNAPSHOT&serialization=java&side=consumer&timeout=15000&timestamp=1552988548773, cause: java.io.StreamCorruptedException: invalid stream header: 77020101

用0.2.1.RELEASE 整合之后   以前一分部接口调用成功了   但是某些接口调用以前的接口出现这错误   其他老的项目（2.6.0）调用这个报错的接口 是没有问题的

**Comment by mercyblitz** [comment]
Please report this issue to [dubbo's issues](https://github.com/apache/incubator-dubbo/issues/)
