### ISSUE TITLE
springboot dubbo consumer, @reference with the registry, multi registries does not work.(多注册中心，在springboot dubbo consumer 端失败)

### ISSUE THREAD

**Issue by dongdongqin** [apache/incubator-dubbo-spring-boot-project#472]
dubbo.registries.shanghai.address=zookeeper://10.157.151.40:2181
dubbo.registries.beijing.address=zookeeper://10.157.151.198:2181

@Reference(version = "1.0.0", registry = "zk1-shanghai")
    private BroadCastDemoService intlHelloService;
@EnableDubbo(multipleConfig = true)
The above configuration does not work. dubbo consumer does not check registry by id, and filter other registry.

However, the dubbo provider is fine with configuration above.
please help!

**Comment by mercyblitz** [comment]
`registry` attribute has to associate with a bean name, like "shanghai" or "beijing". However, Provider will registry both if @Service dost not specify.

**Comment by dongdongqin** [comment]
> Consumer's `@Reference#registry()` attribute has to associate with a bean name, like "shanghai" or "beijing". However, Provider will registry both if @service dost not specify.

Thank your for your response.
yes, you are right. However, do you know how can i configure to let  Consumer's `@Reference#registry()` attribute  associated with a bean name, like "shanghai" or "beijing" ?

Because i have requirement, i need to consumer specific zookeeper center!
Hope your response!

**Comment by dongdongqin** [comment]
For example:
dubbo xml,
  <dubbo:registry id="chinaRegistry" address="zookeeper://10.157.151.40:2181" />
    <dubbo:registry id="intlRegistry" address="zookeeper://10.157.151.198:2181" />

    <dubbo:reference id="chinaHelloService" interface="com.mastercard.api.service.BroadCastDemoService" version="1.0.0" cluster="broadcast" registry="chinaRegistry" />
    <dubbo:reference id="intlHelloService" interface="com.mastercard.api.service.BroadCastDemoService" version="1.0.0" cluster="broadcast" registry="intlRegistry" />


From the above configuration,  intlHelloService service only can consume  intlRegistry  register center.

How springboot do like these mentioned above?
thanks !

**Comment by mercyblitz** [comment]
@dongdongqin `@Reference#registry()` is a String array attribute, you can specify two bean names in there.

**Comment by dongdongqin** [comment]
@mercyblitz, i know what your mean. If i type wrong name beans,  springboot dubbo does not have any error.  The default registry center  will be used.
 please see my #473, i have code in github.  
thanks a lot!
