### ISSUE TITLE
Springboot dubbo cannot reference the same name service from different registries

### ISSUE THREAD

**Issue by dongdongqin** [apache/incubator-dubbo-spring-boot-project#473]
From my testing,
i find that Multiple registries have below problems, with springboot. cannot reference the same name service from different registries.

Sample:

  @Reference(registry = {"registry1"}, version = "1.0.0", cluster = "broadcast")
    private DemoService demo2Service;

   @Reference(registry = {"registry2"}, version = "1.0.0", cluster = "broadcast")
    private DemoService demoService;

And we can find that 
(1): service providers for (demoService and demo2Service) are only from registry1.   
or
(2): service providers for (demoService and demo2Service) are only from registry2.

it depends on which one demo2Service or demoService load first.
That is so different from xml config instead of springboot.
please see my #415 description.
I believe that you can do the  simple samples and you will find the problems.

**Comment by dongdongqin** [comment]
please see my github example: https://github.com/dongdongqin/dubbo-springboot-Multiple-registries.git
for above problem.

please help me solve the problems: i want to reference the same name service from different registries with springboot.


xml configuration is supported, please check the official web and my testing is also right:
http://dubbo.apache.org/en-us/docs/user/demos/multi-registry.html

**Comment by mercyblitz** [comment]
Ok, Got it, it should throw an exception and will be fixed in Dubbo 2.7.2

**Comment by ruyuhi** [comment]
我遇到的问题是，本地环境需要调用，本地的dubbo 服务，同时有些功能又得调用测试环境的dubbo服务，所以 我的config 会初始化2个registry, 如下，`
        @Bean("registryConfig")
	public RegistryConfig registryConfig() {
		RegistryConfig registryConfig = new RegistryConfig();
		registryConfig.setDefault(true);
		registryConfig.setAddress(registryAddress);
		return registryConfig;
	}
	
	@Bean("testRegistry")
	public RegistryConfig registryConfigTest() {
		RegistryConfig registryConfig = new RegistryConfig();
		registryConfig.setDefault(false);
		registryConfig.setAddress(registryAddressTest);
		return registryConfig;
	}`

然后代码中注入通过 `
@Reference(registry = "testRegistry", consumer = BaseConstants.DUBBO_CONSUMER_CONFIG_SAAS)
private TenantFacade tenantFacade;`

发现 tenantFacade 中生效的一直是 registryConfig ，而不是 testRegistry。最后查看了 ReferenceBean.class 的afterPropertiesSet 方法 源码，发现在初始化时，只会采用默认的和没有设置false的，代码如下：
`if ((getRegistries() == null || getRegistries().isEmpty())
                && (getConsumer() == null || getConsumer().getRegistries() == null || getConsumer().getRegistries().isEmpty())
                && (getApplication() == null || getApplication().getRegistries() == null || getApplication().getRegistries().isEmpty())) {
            Map<String, RegistryConfig> registryConfigMap = applicationContext == null ? null : BeanFactoryUtils.beansOfTypeIncludingAncestors(applicationContext, RegistryConfig.class, false, false);
            if (registryConfigMap != null && registryConfigMap.size() > 0) {
                List<RegistryConfig> registryConfigs = new ArrayList<RegistryConfig>();
                for (RegistryConfig config : registryConfigMap.values()) {
                    if (config.isDefault() == null || config.isDefault().booleanValue()) {
                        registryConfigs.add(config);
                    }
                }
                if (registryConfigs != null && !registryConfigs.isEmpty()) {
                    super.setRegistries(registryConfigs);
                }
            }
        }`

，我如果要调用不同环境下的dubbo 服务，用@Reference 注解怎么实现呢

**Comment by kexianjun** [comment]
seems the same reason with https://github.com/apache/dubbo/issues/4160
