### ISSUE TITLE
can you support @Reference 's property url   in consumer?

### ISSUE THREAD

**Issue by suiyueqiannian** [apache/incubator-dubbo-spring-boot-project#482]
@Reference has the property url,so we can connect to the provider directly,can you support it as a global config in consumer?

**Comment by mercyblitz** [comment]
Yes, you could.

**Comment by suiyueqiannian** [comment]
@mercyblitz how? I didn‘t find the  property url in consumer config except every reference annotation...
If I want to connect to the provider directly, I should config it in every reference annotation...

**Comment by mercyblitz** [comment]
`@Reference(url=''...")`

**Comment by suiyueqiannian** [comment]
@mercyblitz I mean not config it in every service  but config it in consumer tag.

**Comment by mercyblitz** [comment]
@suiyueqiannian `@Reference(url=''...")` just was injected one by one in client side.

**Comment by NightFarmer** [comment]
我明白 题主的意思是想在配置文件里写上公用的url，省掉@Reference上的url，同问

**Comment by yaoqiang** [comment]
> 我明白 题主的意思是想在配置文件里写上公用的url，省掉@reference上的url，同问

解决了吗？bro
