### ISSUE TITLE
publish a pre-release

### ISSUE THREAD

**Issue by adriancole** [apache/incubator-dubbo-spring-boot-project#49]
It would be nice to have a not-spanshot release, even if version is not 1.0.0. This is better for integrating than snapshots which can change frequently. How about cutting a 0.1.0? or similar?

**Comment by adriancole** [comment]
maybe this is not yet because there is no apache group ID for dubbo, yet? or does this project want to stay as alibaba name?

**Comment by mercyblitz** [comment]
releasing `0.1.0` is a good advice

**Comment by ralf0131** [comment]
@adriancole There is a discussion[1] about what should go into Apache, and I believe this project will be part of the move.

I do have some concern about doing a release while moving into Apache, and I am planning to ask our mentor on the dev list. Maybe we can discuss there. 

[1] https://issues.apache.org/jira/projects/DUBBO/issues/DUBBO-3

**Comment by adriancole** [comment]
The issue you mention is about apache release. You can do 0.1.0 release
under existing group ID, right? For a user, changing group ID is not
difficult, but building from scratch is.

I don't want to put discussion on the issue as it is about IP clearance,
which I don't think this issue affects. We can instead discuss on dev@ if
you prefer. The problem is that the other spring boot starter has a
release, and that alone makes people want to use it. Easy to eliminate this
concern even if it is tentative (ex under alibaba group ID or not
synchronized to maven central, rather sonatype only).

On the other hand, if best to wait till apache transition to release, maybe
this one can release first :) Just sometimes takes month or more before
release is done first time.

**Comment by ralf0131** [comment]
@adriancole I will agree you, but before doing that I would probably confirm with mentors. I would rather keep our release cycle stable since people would expect that. Would you mind discuss it on the @dev list.

**Comment by beiwei30** [comment]
To make it simple, I suggest we should go ahead to release 0.1.0 with the original artificatId so that Adrian’s work will not be blocked. But in this way it also means Adrian needs to revise his work after the transition is done.

Adrian, does this sound reasonable to you? I will propose this suggestion on @dev anyway. If there’s no objection from apache mentor within the following couple of days, let’s do this.

-Ian.

**Comment by adriancole** [comment]
works for me!

**Comment by adriancole** [comment]
bear in mind some changes may need to occur, so let's plan on more
than one interim release :P

**Comment by beiwei30** [comment]
Correct. In order to avoid it, could you pls. start your work with the snapshot version, and feed us your feedback as much as possible? :) You could talk to Mercy (@mercyblitz) directly.

Thanks,
-Ian.

**Comment by luffyke** [comment]
Agree with @adriancole

**Comment by mercyblitz** [comment]
@adriancole We will release 0.1.0 in next week.

**Comment by mercyblitz** [comment]
Released
```xml
<dependency>
  <groupId>com.alibaba.boot</groupId>
  <artifactId>dubbo-spring-boot-starter</artifactId>
  <version>0.1.0</version>
</dependency>
```
