### ISSUE TITLE
已经严重对滞后于 dubbo 和 springboot 的版本

### ISSUE THREAD

**Issue by yutaoxu** [apache/incubator-dubbo-spring-boot-project#57]
1. dubbo 目前最新版本为 2.6.0
2. springboot 目前最新版本为 2.0.0.release

**Comment by flystarfly** [comment]
这个版本不兼容springboot2.0.0.release。配置好了之后会报错：java.lang.NoClassDefFoundError: org/springframework/boot/bind/RelaxedPropertyResolver

**Comment by mercyblitz** [comment]
Application can upgrade dubbo `2.6.0` ,  and will support Springboot 2.0.0

**Comment by yutaoxu** [comment]
when to release 0.1.1 ?

**Comment by mercyblitz** [comment]
@yutaoxu next week, It's possible to release two versions supporting Spring Boot 1.x and 2.0.

**Comment by levin950825** [comment]
@mercyblitz 什么时候修复 issues 的 bug呢

**Comment by luffyke** [comment]
@levin950825 which issue with bug?

**Comment by neesonqk** [comment]
@mercyblitz when will release the version supporting 2.0? thx

**Comment by oawang** [comment]
mark. 请问如何配置一个项目既是消费者，又是提供者[https://github.com/apache/incubator-dubbo-spring-boot-project/issues/66](url)

**Comment by mercyblitz** [comment]
@oawang  please attach code !

**Comment by mercyblitz** [comment]
Duplicated #37
