### ISSUE TITLE
服务提供者在 yml 文件中配置的端口没有重写默认端口 20880

### ISSUE THREAD

**Issue by yutaoxu** [apache/incubator-dubbo-spring-boot-project#58]
服务提供者在 yml 文件中配置的端口没有重写默认端口 20880，比如：
dubbo:
#  scan:
#    base-packages: com.riil.labs.app.service.impl
  registry:
    id: zookeeper
    address: zookeeper://x.x.x.x:2181
  protocol:
    id: dubbo
    name: dubbo
    port: 28888
    status: server
  application:
    id: serivce-provider
    name: serivce-provider

在 dubbo admin 可以发现端口仍然为 20880,而不是 28888

![image](https://user-images.githubusercontent.com/4257762/37381264-2559540e-2777-11e8-8524-42bf48997903.png)

**Comment by luffyke** [comment]
Duplicate with #30

**Comment by lovepoem** [comment]
Now https://github.com/alibaba/dubbo/milestone/13 is released. dubbo 2.6.1 has fixed this bug，you can use 2.6.1 to have a try

**Comment by leokoon** [comment]
I got the same problem， When will the problem be repaired?

**Comment by xhh1314** [comment]
thank you, I have  solved this problem  after dubbo replaced  the version with 2.6.1

**Comment by mercyblitz** [comment]
Checkout master and build source , please wait for our release in Apache repository.
