### ISSUE TITLE
dubbo的  check 没有起作用

### ISSUE THREAD

**Issue by zondahuman** [apache/incubator-dubbo-spring-boot-project#59]
以前非spring boot使用的时候，在consumer里面配置了check=false，provider没启动，consumer启动时候不会报错，貌似现在这个spring boot版本没有起作用，不管是在application..yml里面
dubbo:  
      registry: ## RegistryConfig Bean
                  id: dubbo-registry
                  address: zookeeper://172.16.2.1:2181
                  group: businessRegistryCenter
                  check: false
还是在

    @Reference(
            application = "${dubbo.application.id}",
            registry = "${dubbo.registry.id}"
          check = false
    )
    SpringBootDubboService springBootDubboService;
这里设置，都不起作用，不清楚是不是我使用有误导致的，反正目前这样子，我停掉了provider，consumer一直报错

**Comment by foreveryang321** [comment]
can try dubbo.consumer.check=false

**Comment by zondahuman** [comment]
@foreveryang321    What you Said does not work .    the check function  should  have been setted in my consumer service .

**Comment by luffyke** [comment]
use properties file instead of yml file in 0.1.0 version as there is a bug for yml.
see here #30

**Comment by zondahuman** [comment]
@luffyke  ，oh， i  see， thank you

**Comment by mercyblitz** [comment]
duplicated #30
