### ISSUE TITLE
多registry是怎么使用的

### ISSUE THREAD

**Issue by EonianGlutton** [apache/incubator-dubbo-spring-boot-project#62]
dubbo start 版本如图
![default](https://user-images.githubusercontent.com/10543696/37460725-0c37172a-2887-11e8-8f21-3dd3ffb8b1b7.png)

问题：
1、application.properties该怎么配？
2、配过之后，在Reference中怎么使用？使用$符读不到啊，${dubbo.application.id}"可以读到，${dubbo.registry.0}就不可以。配置文件中两个是都有的
@Reference(version = "1.0.0",
            application = "${dubbo.application.id}",
            registry = "${dubbo.registry.0}",
            check = false
    )

**Comment by mercyblitz** [comment]
`registry` attribute can't support placeholder now, it will support in next release , and you can define multiple value on this attribute method.

**Comment by EonianGlutton** [comment]
I found another method to use multiple refistries
In properties：
dubbo.config.multiple=true
dubbo.applications.applicationredis.name = dubbo-provider-demo2
dubbo.registries.registryredis.address = zookeeper://192.168.1.x:3181
dubbo.applications.applicationbus.name = dubbo-provider-demo
dubbo.registries.registrybus.address = zookeeper://172.28.32.x:9911
dubbo.protocols.protocol1.name = dubbo
dubbo.protocols.protocol1.port = 20880

In controller:
@Reference(version = "1.0.0",
            application = "applicationbus",
            registry = "registryredis",
            check = false
    )

use in this way is ok.

But there is one question:
1.I use bean name in controller,is that bean name must start with application?If I change the prefix,it does not work.


thank you very much!

**Comment by mercyblitz** [comment]
Duplicated with #30
