### ISSUE TITLE
Replace META-INF/spring-configuration-metadata.json manually

### ISSUE THREAD

**Issue by mercyblitz** [apache/incubator-dubbo-spring-boot-project#63]
To replace `META-INF/spring-configuration-metadata.json` manually instead of auto-generation.

**Comment by duming08899** [comment]
该项目是否可以投入到生产环境中，查看aliyun的Maven私服已经到了dubbo-spring-boot 2.0版本,0.11本周什么时间点可以发布。

**Comment by ralf0131** [comment]
Hi, 

Welcome!

Would you please consider ask in English? Since this project is moved to ASF repo, we hope it is understandable by people all over the world so that everyone can join to discuss.

**Comment by duming08899** [comment]
Whether the project can be put into production environment, we can see that aliyun's Maven private clothing has arrived in dubbo-spring-boot 2 version, and 0.11 what time can we release this week?

**Comment by mercyblitz** [comment]
@duming08899  I will commit code in this week,  will release one in next week.
