### ISSUE TITLE
Infer dubbo configuration without classpath scanning

### ISSUE THREAD

**Issue by adriancole** [apache/incubator-dubbo-spring-boot-project#68]
In the other dubbo starter, I add `@EnableDubboConfiguration` to the below, and it automatically configures the reference. I'd like a reference (which is a dubbo type for sure) to automatically be provided, whether this is due to something similar to `@EnableDubboConfiguration` or otherwise.

I don't want to hard-code string-based package names, as for example I have something here scoped to a class. I'd like this to be smart and not require maintenance (similar to how spring boot allows you to use `@Import` as necessary to be explicit.

```
@EnableAutoConfiguration
@RestController
@CrossOrigin // So that javascript can be hosted elsewhere
public class Frontend {

  @Reference(url = "dubbo://127.0.0.1:9000") Api api;

  @RequestMapping("/") public String callBackend() {
    return api.printDate();
  }

  public static void main(String[] args) {
    SpringApplication.run(Frontend.class,
        "--spring.application.name=frontend",
        "--server.port=8081"
    );
  }
}
```

**Comment by mercyblitz** [comment]
If `Frontend` was scanned as Spring `@Component` ,  `@Reference` properties will be injected, like `@Autowired`, which has been implemented by Dubbo

**Comment by mercyblitz** [comment]
* `@DubboComponentScan` is like Spring Boot's `@ServletComponentScan` * `ReferenceAnnotationBeanPostProcessor` will handle Dubbo Service Bean injection that `DubboAutoConfiguration` will register on startup

**Comment by luffyke** [comment]
@adriancole, do you mean use Annotation instead of config ```dubbo.scan.basePackages  = me.kexitang.dubbo.boot.demo.service``` in config file, such as ```@EnableDubboConfiguration``` in another dubbo-starter project(i guess [alibaba/dubbo-spring-boot-starter](https://github.com/alibaba/dubbo-spring-boot-starter))?

@mercyblitz pls correct below sentence to remove Reference in README because Reference not need to scan as you said.
```
# Base packages to scan Dubbo Components (e.g @Service , @Reference)
```
and i suggest to use Annotation instead of config **dubbo.scan.basePackages**.

**Comment by adriancole** [comment]
Basically I want to be precise within a package.. explicitly not try to
wire things that happen to be in same package.

**Comment by mercyblitz** [comment]
@luffyke Annotation and `dubbo.scan.basePackages` property both works fine.

1. If prefer to annotation-driven , `@DubboComponentScan` scans `@Service`

2. All `@Reference` injections does not depend on `dubbo.scan.basePackages` or `@DubboComponentScan` in Spring Boot application. it only requires `@Reference` declaring class is a valid `@Component` class or its' variants.

3.  The usage of `@DubboComponentScan` is same as `@ComponentScan` , all attributes are optional. If `com.acme.Comfiguration` annotated `@ComponentScan` , all valid `@Component` class or its' variants class will be scanned.

**Comment by mercyblitz** [comment]
In a word ,  Dubbo's `@Service` is like Spring's `@Service` ,and `@Reference` is like `@Autowired`.

**Comment by adriancole** [comment]
I think requiring scanning of `@Service` is still too loose.

For example, in normal web-mvc I can have a `@RestController` annotation on two different spring boot applications in the same package and they will not load eachother's endpoints. package-based scanning is unnecessarily loose and will cause other types in the same package to accidentally load eachother.

`@Reference` not being scanned is good, but as I understand it only solves clients. So, we are still stuck scanning for services!

**Comment by adriancole** [comment]
I take my last statement back. It seems you have to redundantly add `@EnableDubbo` even if your boot application is already annotated with `@Service`. This is different than the previous boot starter which is easier as you don't have to do this.
