### ISSUE TITLE
How to use with zookeeper

### ISSUE THREAD

**Issue by chenwenzhang** [apache/incubator-dubbo-spring-boot-project#75]
How to use with zookeeper

**Comment by Jukewu** [comment]
you can refer to #61  or 

> dubbo.registry.id=xxxx
> dubbo.registry.protocol=zookeeper
> dubbo.registry.address=192.168.86.119
> dubbo.registry.port=2184
> dubbo.registry.client=curator

**Comment by chenwenzhang** [comment]
@Jukewu thank you

**Comment by luffyke** [comment]
Duplicated with #61
