### ISSUE TITLE
请问2.0什么时候能出来啊？

### ISSUE THREAD

**Issue by c297186864** [apache/incubator-dubbo-spring-boot-project#76]
如题，请问2.0什么事出来，https://github.com/alibaba/dubbo-spring-boot-starter  这个项目是你们的吗

**Comment by luffyke** [comment]
Please use English when firing issue as Dubbo has been a apache incubator project.
Support Spring Boot 2.0 question is duplicated with #71 
This dubbo-spring-boot-project is official project, dubbo-spring-boot-starter under alibaba group is 3rd support project.

**Comment by c297186864** [comment]
ok

**Comment by ralf0131** [comment]
Hi, you can ask by sending an email to dev@dubbo.apache.org , issues are used to track bugs.
