### ISSUE TITLE
Dubbo Endpoint无法访问

### ISSUE THREAD

**Issue by 249510573** [apache/incubator-dubbo-spring-boot-project#80]
项目中导入spring-boot-starter-parent(1.5.1.RELEASE)、spring-boot-starter-dubbo、spring-boot-actuator等，无法访问http://localhost:8080/dubbo。

**Comment by mercyblitz** [comment]
Please use https://github.com/apache/incubator-dubbo-spring-boot-project/tree/0.1.x
