### ISSUE TITLE
The bug of configuration in application.yml

### ISSUE THREAD

**Issue by fuyongde** [apache/incubator-dubbo-spring-boot-project#82]
The Configuration `dubbo.protocol.port` does't work if configured in `application.yml`, you should configure it  in  `application.properties` to put it into effect

**Comment by mercyblitz** [comment]
It will fix on dubbo 2.5.11+

**Comment by leyou240** [comment]
@mercyblitz What about 2.6.x? It will also fix?

**Comment by mercyblitz** [comment]
Checkout master and build source , please wait for our release in Apache repository.
