### ISSUE TITLE
当我项目中使用了多个 protocol ，如何在配置中配置？

### ISSUE THREAD

**Issue by tucke** [apache/incubator-dubbo-spring-boot-project#86]
如何优雅的配置多个自定义 protocol 在 application.properties 中？

**Comment by mercyblitz** [comment]
Please take a look at this : https://github.com/mercyblitz/blogs/blob/master/java/dubbo/Dubbo-Externalized-Configuration.md#%E5%A4%9A-dubbo-%E9%85%8D%E7%BD%AE-bean-%E7%BB%91%E5%AE%9A

**Comment by tucke** [comment]
谢谢！
