### ISSUE TITLE
有人在用吗？能用于生产环境吗？

### ISSUE THREAD

**Issue by rememberber** [apache/incubator-dubbo-spring-boot-project#87]
有人将这个应用于生产吗？

**Comment by ralf0131** [comment]
Hi, welcome!

Would you please update the title and description using English? Dubbo is a global community and we would like the issue to be seen by people all over the world.

Questions like this are expected to be asked in the mailing list, you can [subscribe](https://github.com/apache/incubator-dubbo/issues/1393) and ask there.
