### ISSUE TITLE
log4j替换成logback了吗？

### ISSUE THREAD

**Issue by rememberber** [apache/incubator-dubbo-spring-boot-project#88]
log4j替换成logback了吗？如果没有，有什么时候替换的打算吗？
如果想贡献代码的话，怎么提交merge请求？

**Comment by ralf0131** [comment]
Hi, welcome!

Would you please update the title and description using English? Dubbo is a global community and we would like the issue to be seen by people all over the world.

Questions like this are expected to be asked in the mailing list, you can [subscribe](https://github.com/apache/incubator-dubbo/issues/1393) and ask there.
