### ISSUE TITLE
Is log4j replaced by logback?

### ISSUE THREAD

**Issue by rememberber** [apache/incubator-dubbo-spring-boot-project#90]
Is log4j replaced by logback? If not, is there any time to plan for replacement?

If I want to contribute code, how do I submit the merge request?

**Comment by lovepoem** [comment]
I think http://dubbo.io/books/dubbo-user-book-en/demos/logger-strategy.html will help you .

**Comment by mercyblitz** [comment]
We recommend logback as a low-level logging system for Spring Boot application
