### ISSUE TITLE
how to register consumer to zookeeper

### ISSUE THREAD

**Issue by halochen90** [apache/incubator-dubbo-spring-boot-project#92]
![image](https://user-images.githubusercontent.com/24949689/38161270-97ed1eb2-34fe-11e8-912a-97205341ac63.png)

![image](https://user-images.githubusercontent.com/24949689/38161296-001f6f12-34ff-11e8-860a-19c528976e62.png)

when i started the dubbo-spring-boot-samples，the provider was registered to zookeeper successfully, but the consumer failed ,why?

**Comment by MichaelDarKnight** [comment]
I meet the same problem, someone could give some suggestions please! thanks!

**Comment by MichaelDarKnight** [comment]
by the way, Mr halochen90, do you resolve your problem with register consumer to zookeeper.

**Comment by MichaelDarKnight** [comment]
oh, it's the conflict of the spring boot version.
