### ISSUE TITLE
为什么运行demo，显示dubbo版本是2.0.1

### ISSUE THREAD

**Issue by yuanruomu** [apache/incubator-dubbo-spring-boot-project#94]
打印的日志
 :: Dubbo Spring Boot (v1.0.0) : https://github.com/dubbo/dubbo-spring-boot-project
 :: Dubbo (v2.0.1) : https://github.com/alibaba/dubbo
 :: Google group : http://groups.google.com/group/dubbo

dubbo admin里面显示

服务地址:   dubbo://192.168.100.173:20885/com.alibaba.boot.dubbo.demo.consumer.DemoService?anyhost=true&application=dubbo-provider-demo&dubbo=2.0.1&generic=false&interface=com.alibaba.boot.dubbo.demo.consumer.DemoService&methods=sayHello&pid=12016&revision=1.0.0&side=provider&status=server×tamp=1522633961753&version=1.0.0
 
注册出来的dubbo版本都是2.0.1

**Comment by suclogger** [comment]
It's a bug of dubbo, please refer https://github.com/apache/incubator-dubbo/issues/1524.
