### ISSUE TITLE
idea调试模式项目启动不起来，正常启动没问题

### ISSUE THREAD

**Issue by LiruiBryant** [apache/incubator-dubbo-spring-boot-project#95]
DubboConfigBindingBeanPostProcessor.postProcessBeforeInitialization(73) | The properties of bean [name : name] have been binding by values : [bean property 'id', bean property 'name']
DubboConfigBindingBeanPostProcessor.postProcessBeforeInitialization(73) | The properties of bean [name : com.alibaba.dubbo.config.RegistryConfig#0] have been binding by values : [bean property 'address', bean property 'protocol']
DubboConfigBindingBeanPostProcessor.postProcessBeforeInitialization(73) | The properties of bean [name : dubbo] have been binding by values : [bean property 'id', bean property 'name', bean property 'port', bean property 'threads']
DubboConfigBindingBeanPostProcessor.postProcessBeforeInitialization(73) | The properties of bean [name : com.alibaba.dubbo.config.MonitorConfig#0] have been binding by values : [bean property 'protocol']
DubboConfigBindingBeanPostProcessor.postProcessBeforeInitialization(73) | The properties of bean [name : com.alibaba.dubbo.config.ProviderConfig#0] have been binding by values : [bean property 'retries', bean property 'filter']

**Comment by mercyblitz** [comment]
Which project you start in IDEA?
