### ISSUE TITLE
how to compile the dubbo-spring-boot-project-0.2.0?

### ISSUE THREAD

**Issue by tinnkm** [apache/incubator-dubbo-spring-boot-project#96]
why can't find the type of AbstractDubboConfigBinder ?

**Comment by suclogger** [comment]
You have to compile and local install dubbo 2.5.11 from @mercyblitz 's repository : https://github.com/mercyblitz/dubbo/tree/2.5.11 first.

**Comment by tinnkm** [comment]
i will try，thanks！
