### ISSUE TITLE
how to configure multiple protocols

### ISSUE THREAD

**Issue by ron-shaw** [apache/incubator-dubbo-spring-boot-project#98]
application.properties:
`
dubbo.config.multiple=true
#
dubbo.protocols[dubbo].id = dubbo
dubbo.protocols[dubbo].name = dubbo
dubbo.protocols[dubbo].port = 23456
dubbo.protocols[dubbo].status = server
#
dubbo.protocols[hessian].id = hessian
dubbo.protocols[hessian].name = hessian
dubbo.protocols[hessian].port = 12346
dubbo.protocols[hessian].status = server
`

it does not work fine.
what can i do?

**Comment by zeng54088** [comment]
I  want to know this problem too

**Comment by zeng54088** [comment]
@SpringBootApplication
@EnableDubboConfig(multiple = true) 
public class DubboProviderDemo {
    public static void main(String[] args) {
        SpringApplication.run(DubboProviderDemo.class,args);
    }
}



## ProtocolConfig Bean
dubbo.protocols.dubbo.name = dubbo
dubbo.protocols.dubbo.port = 20880
dubbo.protocols.dubbo.status = server

dubbo.protocols.rmi.name = rmi
dubbo.protocols.rmi.port = 1099
dubbo.protocols.rmi.status = server

**Comment by mercyblitz** [comment]
```properties
dubbo.protocols[hessian].id = hessian
dubbo.protocols[hessian].name = hessian
dubbo.protocols[hessian].port = 12346
dubbo.protocols[hessian].status = server
```
Does not work...
